Repository concord-consortium/codap, pull requests merged in 2023-03, with the labels that each got.

#670 Adding 2 additional containers so that cypress tests can run in parallel
  .github/workflows/v3.yml
Labels: v3

#673 184392252-restore graph components
  v3/src/components/axis/axis-types.ts
  v3/src/components/axis/components/axis-drag-rects.tsx
  v3/src/components/axis/hooks/use-axis.ts
  v3/src/components/axis/models/axis-model.test.ts
  v3/src/components/axis/models/axis-model.ts
  v3/src/components/codap-component.tsx
  v3/src/components/graph/components/chartdots.tsx
  v3/src/components/graph/components/dotplotdots.tsx
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/components/scatterdots.tsx
  v3/src/components/graph/hooks/use-graph-controller.ts
  v3/src/components/graph/models/data-configuration-model.test.ts
  v3/src/components/graph/models/data-configuration-model.ts
  v3/src/components/graph/models/graph-controller.ts
  v3/src/components/graph/models/graph-layout.ts
  v3/src/components/graph/models/graph-model.ts
Labels: v3

#676 Restoration of proper GraphLayoutContext
  v3/src/components/axis/hooks/use-axis-bounds.ts
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/graph/hooks/use-graph-controller.ts
  v3/src/components/graph/models/graph-controller.ts
  v3/src/components/graph/models/graph-layout.ts
Labels: v3

#672 Fix React Hooks linter errors not applying when mobx-state-tree observerComponent is not given a named function
  v3/src/components/app.tsx
  v3/src/components/axis/components/axis-drag-rects.tsx
  v3/src/components/axis/components/droppable-axis.tsx
  v3/src/components/data-summary/data-summary.tsx
  v3/src/components/free-tile-row.tsx
  v3/src/components/graph/components/graph-axis.tsx
  v3/src/components/graph/components/inspector-panel/point-format-panel.tsx
  v3/src/components/graph/components/marquee.tsx
  v3/src/components/mosaic-tile-row.tsx
  v3/src/components/slider/editable-slider-value.tsx
  v3/src/components/slider/slider-component.tsx
  v3/src/components/slider/slider-thumb.tsx
  v3/src/components/slider/slider-title-bar.tsx
Labels: bug, v3

#678 refactor: add CollectionProps model; add jest tests
  v3/src/models/codap/create-codap-document.test.ts
  v3/src/models/data/attribute.test.ts
  v3/src/models/data/collection.test.ts
  v3/src/models/data/collection.ts
  v3/src/models/data/data-set.test.ts
  v3/src/models/data/data-set.ts
Labels: v3

#677 Render sub-table title bars (and case count)
  v3/package-lock.json
  v3/package.json
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-table/collection-table.tsx
Labels: enhancement, dependencies, javascript, v3

#679 Add basic scrolling to case table
  v3/src/components/case-table/case-table.scss
Labels: enhancement, javascript, v3

#674 feat: support expand/collapse of parent cases in hierarchical table
  .github/workflows/v3.yml
  v3/src/components/case-table/case-table-component.test.tsx
  v3/src/components/case-table/case-table-component.tsx
  v3/src/components/case-table/case-table-model.ts
  v3/src/components/case-table/case-table-types.ts
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-table/case-table.tsx
  v3/src/components/case-table/collection-table-spacer.tsx
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-table/edit-attribute-properties.tsx
  v3/src/components/case-table/new-collection-drop.tsx
  v3/src/components/case-table/use-columns.tsx
  v3/src/components/case-table/use-index-column.tsx
  v3/src/components/case-table/use-rows.ts
  v3/src/hooks/use-collection-context.ts
  v3/src/hooks/use-data-set-and-metadata.ts
  v3/src/models/data/data-set-types.ts
  v3/src/models/data/data-set.ts
  v3/src/utilities/css-utils.ts
Labels: v3

#685 refactor: improve CollectionPropsModel integration
  v3/package-lock.json
  v3/package.json
  v3/src/components/case-table/case-table.tsx
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-table/column-header-divider.tsx
  v3/src/components/case-table/use-columns.tsx
  v3/src/components/case-table/use-index-column.tsx
  v3/src/components/case-table/use-selected-rows.ts
  v3/src/hooks/use-collection-context.ts
  v3/src/models/codap/create-codap-document.test.ts
  v3/src/models/data/collection.test.ts
  v3/src/models/data/collection.ts
  v3/src/models/data/data-set-collection-groups.test.ts
  v3/src/models/data/data-set-utils.ts
  v3/src/models/data/data-set.ts
Labels: v3

#686 feat: implement focused tile; title bar, inspector, and resize UI based on focused tile
  v3/src/components/app.scss
  v3/src/components/calculator/calculator-title-bar.tsx
  v3/src/components/case-table/case-table-component.tsx
  v3/src/components/case-table/case-table-title-bar.scss
  v3/src/components/case-table/case-table-title-bar.tsx
  v3/src/components/case-table/case-table.tsx
  v3/src/components/codap-component.tsx
  v3/src/components/component-title-bar.scss
  v3/src/components/component-title-bar.tsx
  v3/src/components/data-summary/data-summary-title-bar.tsx
  v3/src/components/free-tile-row.tsx
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/graph/components/graph-title-bar.tsx
  v3/src/components/graph/components/graph.tsx
  v3/src/components/hello/hello-title-bar.tsx
  v3/src/components/hello/hello.scss
  v3/src/components/hello/hello.tsx
  v3/src/components/slider/slider-title-bar.tsx
  v3/src/components/tiles/placeholder/placeholder-tile-title-bar.tsx
  v3/src/components/vars.scss
  v3/src/models/document/free-tile-row.ts
  v3/src/models/ui-state.ts
  v3/src/theme.ts
Labels: v3

#680 184210651 new tiles
  v3/src/components/app.tsx
  v3/src/components/calculator/calculator-registration.ts
  v3/src/components/case-table/case-table-registration.ts
  v3/src/components/graph/graph-registration.ts
  v3/src/components/slider/slider-registration.ts
  v3/src/components/tool-shelf/tool-shelf.tsx
  v3/src/models/document/document-content.ts
  v3/src/models/tiles/tile-component-info.ts
Labels: v3

#690 feat: typed ids for more readable document export
  v3/src/components/calculator/calculator-registration.ts
  v3/src/components/case-table/case-table-registration.ts
  v3/src/components/data-summary/data-summary-registration.ts
  v3/src/components/graph/adornments/adornment-models.ts
  v3/src/components/graph/graph-registration.ts
  v3/src/components/graph/models/data-configuration-model.ts
  v3/src/components/graph/models/new-graph-model.ts
  v3/src/components/graph/models/plot-model.ts
  v3/src/components/hello/hello-registration.ts
  v3/src/components/slider/slider-registration.ts
  v3/src/models/codap/add-default-content.ts
  v3/src/models/codap/create-codap-document.test.ts
  v3/src/models/data/attribute.ts
  v3/src/models/data/collection.ts
  v3/src/models/data/data-set-collection-groups.test.ts
  v3/src/models/data/data-set.ts
  v3/src/models/data/global-value.ts
  v3/src/models/document/document.ts
  v3/src/models/document/mosaic-tile-row.test.ts
  v3/src/models/document/mosaic-tile-row.ts
  v3/src/models/document/shared-model-document-manager.test.ts
  v3/src/models/document/tile-row.ts
  v3/src/models/history/tree-manager.test.ts
  v3/src/models/history/undo-store.test.ts
  v3/src/models/shared/shared-case-metadata.test.ts
  v3/src/models/shared/shared-model.ts
  v3/src/models/tiles/placeholder/placeholder-registration.ts
  v3/src/models/tiles/tile-content-info.ts
  v3/src/models/tiles/tile-model.ts
  v3/src/models/tiles/unknown-content-registration.ts
  v3/src/test/test-tile-content.ts
  v3/src/utilities/js-utils.ts
Labels: v3

#687 Upgrade react-data-grid to 7.0.0-beta.26
  v3/package-lock.json
  v3/package.json
  v3/patches/react-data-grid+7.0.0-beta.26.patch
  v3/src/components/case-table/case-table-types.ts
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-table/use-selected-rows.ts
Labels: dependencies, v3

#691 184667117 find open area - V3
  v3/src/components/tool-shelf/tool-shelf.tsx
  v3/src/utilities/view-utils.ts
Labels: v3

#695 feat: import calculator; better support for non-resizable tiles
  v3/src/components/app.tsx
  v3/src/components/calculator/calculator-model.ts
  v3/src/components/calculator/calculator-registration.ts
  v3/src/components/calculator/calculator.scss
  v3/src/components/case-table/case-table-registration.ts
  v3/src/components/case-table/case-table.tsx
  v3/src/components/codap-component.scss
  v3/src/components/codap-component.tsx
  v3/src/components/constants.ts
  v3/src/components/free-tile-component.tsx
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/graph/graph-registration.ts
  v3/src/components/graph/graphing-types.ts
  v3/src/components/graph/models/graph-layout.ts
  v3/src/components/mosaic-tile-row.tsx
  v3/src/components/slider/slider-registration.ts
  v3/src/components/slider/slider.scss
  v3/src/components/tool-shelf/tool-shelf.tsx
  v3/src/models/codap/add-default-content.ts
  v3/src/models/document/free-tile-row.ts
  v3/src/models/tiles/tile-component-info.ts
  v3/src/v2/calculator.codap
  v3/src/v2/codap-v2-import.test.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3

#696 feat: click on background deselects focused tile
  v3/src/components/free-tile-row.tsx
  v3/src/models/ui-state.ts
Labels: v3

#697 Update node to use version 16, Add timeout on npm start to avoid cyress job to timeout
  .github/workflows/v3.yml
Labels: v3

#700 Update dependencies; eliminate vulnerability warnings
  .github/workflows/v3.yml
  v3/cypress/e2e/axis.spec.ts
  v3/package-lock.json
  v3/package.json
  v3/patches/mobx-state-tree+5.1.8.patch
  v3/patches/react-data-grid+7.0.0-beta.27.patch
  v3/src/components/tool-shelf/tool-shelf.test.tsx
  v3/src/components/tool-shelf/tool-shelf.tsx
  v3/src/models/data/data-set-collection-groups.test.ts
  v3/src/models/history/tree-manager.test.ts
  v3/src/models/history/tree-manager.ts
  v3/src/models/history/undo-store.test.ts
Labels: v3

#711 V3: Allows tiles to be closed without focusing on tile
  v3/src/components/calculator/calculator-title-bar.tsx
  v3/src/components/case-table/case-table-title-bar.tsx
  v3/src/components/data-summary/data-summary-title-bar.tsx
  v3/src/components/graph/components/graph-title-bar.tsx
  v3/src/components/slider/slider-title-bar.tsx
  v3/src/components/tiles/placeholder/placeholder-tile-title-bar.tsx
Labels: v3

#712 Adds snap to grid using dnd-kit's modifiers
  v3/package-lock.json
  v3/package.json
  v3/src/components/codap-dnd-context.tsx
  v3/src/hooks/use-drag-drop.ts
Labels: v3

#718 V3: Refactors close and minimize buttons to the component title bar
  v3/src/components/calculator/calculator-title-bar.tsx
  v3/src/components/case-table/case-table-title-bar.tsx
  v3/src/components/component-title-bar.scss
  v3/src/components/component-title-bar.test.tsx
  v3/src/components/component-title-bar.tsx
  v3/src/components/data-summary/data-summary-registration.ts
  v3/src/components/data-summary/data-summary-title-bar.tsx
  v3/src/components/graph/components/graph-title-bar.tsx
  v3/src/components/graph/graph-registration.ts
  v3/src/components/slider/slider-title-bar.tsx
  v3/src/components/tiles/placeholder/placeholder-tile-title-bar.tsx
  v3/src/components/tiles/tile-base-props.ts
  v3/src/models/tiles/placeholder/placeholder-registration.ts
  v3/src/models/tiles/unknown-content-registration.ts
Labels: v3

#717 Dropping categorical attribute on top or right splits graph into subplots
  v3/src/components/axis/axis-types.ts
  v3/src/components/axis/axis-utils.test.ts
  v3/src/components/axis/axis-utils.ts
  v3/src/components/axis/components/axis-drag-rects.tsx
  v3/src/components/axis/components/axis-or-legend-attribute-menu.tsx
  v3/src/components/axis/components/axis.tsx
  v3/src/components/axis/components/sub-axis.tsx
  v3/src/components/axis/hooks/use-axis.test.tsx
  v3/src/components/axis/hooks/use-axis.ts
  v3/src/components/axis/hooks/use-sub-axis.ts
  v3/src/components/axis/models/axis-layout-context.ts
  v3/src/components/axis/models/axis-model.ts
  v3/src/components/axis/models/multi-scale.ts
  v3/src/components/graph/components/attribute-label.tsx
  v3/src/components/graph/components/casedots.tsx
  v3/src/components/graph/components/chartdots.tsx
  v3/src/components/graph/components/dotplotdots.tsx
  v3/src/components/graph/components/droppable-add-attribute.tsx
  v3/src/components/graph/components/droppable-plot.tsx
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/graph/components/graph.scss
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/components/legend/legend.tsx
  v3/src/components/graph/components/scatterdots.tsx
  v3/src/components/graph/graphing-types.ts
  v3/src/components/graph/hooks/use-init-graph-layout.ts
  v3/src/components/graph/models/data-configuration-model.ts
  v3/src/components/graph/models/graph-controller.ts
  v3/src/components/graph/models/graph-layout.ts
  v3/src/components/slider/slider-component.tsx
  v3/src/components/slider/slider-layout.ts
  v3/src/components/slider/slider-thumb.tsx
  v3/src/hooks/use-drop-hint-string.ts
Labels: v3

#726 184814780 & 184077414
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/graph/components/graph.scss
  v3/src/components/graph/models/graph-layout.ts
  v3/src/utilities/view-utils.ts
Labels: v3

#727 Fix merge mistake
  v3/src/components/graph/models/graph-layout.ts
Labels: v3

#730 chore: fix cypress tests
  v3/cypress/support/commands.ts
  v3/cypress/support/elements/axis-elements.ts
  v3/cypress/support/elements/legend-elements.ts
  v3/src/components/axis/components/axis-or-legend-attribute-menu.tsx
  v3/src/components/axis/components/sub-axis.tsx
  v3/src/models/data/category-set.test.ts
Labels: v3

#728 animation fix
  v3/src/components/graph/components/dotplotdots.tsx
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/components/scatterdots.tsx
  v3/src/components/graph/hooks/use-graph-model.ts
  v3/src/components/graph/hooks/use-plot.ts
  v3/src/components/graph/utilities/graph-utils.ts
Labels: v3

#731 184805909-changing graph attributes issues-v3
  v3/src/components/axis/hooks/use-sub-axis.ts
  v3/src/components/axis/models/multi-scale.ts
Labels: v3

#732 184847177-axis-reversal-bug-v3
  v3/src/components/axis/components/axis-drag-rects.tsx
Labels: v3
