Repository concord-consortium/codap, pull requests merged in 2024-11, with the labels that each got.

#1586 V3 release 3.0.0 pre.1963
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1582 fix: selection of first argument after inserting function from list
  v3/src/components/common/formula-editor-context.tsx
Labels: v3, run regression

#1587 fix: sorting of hierarchical data sets
  v3/src/models/data/data-set-undo.ts
  v3/src/models/data/data-set.test.ts
  v3/src/models/data/data-set.ts
  v3/src/models/document/create-document-model.ts
  v3/src/models/tiles/tile-environment.ts
  v3/src/utilities/translation/locale.ts
Labels: v3, run regression

#1585 Add "Esc" and "Cmd-Enter" handler to the formula editor.
  v3/cypress/cypress.d.ts
  v3/cypress/support/commands.ts
  v3/cypress/support/elements/table-tile.ts
  v3/src/components/common/edit-formula-modal.tsx
  v3/src/components/common/formula-editor.tsx
  v3/src/utilities/platform-utils.ts
Labels: v3, run regression

#1583 Adds '=' to formula editor modal
  v3/src/components/common/edit-formula-modal.scss
  v3/src/components/common/edit-formula-modal.tsx
Labels: v3

#1564 CFM dirty document support
  v3/README.md
  v3/cypress/e2e/cfm.spec.ts
  v3/cypress/e2e/table.spec.ts
  v3/cypress/support/elements/cfm.ts
  v3/src/components/app.tsx
  v3/src/lib/debug.ts
  v3/src/lib/handle-cfm-event.test.ts
  v3/src/lib/handle-cfm-event.ts
  v3/src/lib/use-cloud-file-manager.ts
  v3/src/models/app-state.ts
  v3/src/models/document/document.ts
  v3/src/models/history/tree-manager.ts
  v3/src/models/history/tree-monitor.ts
Labels: v3, run regression

#1589 Fix restored layout of graph of categorical axis
  v3/src/components/axis/hooks/use-axis.ts
Labels: v3, run regression

#1576 188445579 update dependencies; node compatibility
  v3/cypress/e2e/graph.spec.ts
  v3/package-lock.json
  v3/package.json
  v3/src/components/app.scss
  v3/src/components/case-card/case-attr-view.scss
  v3/src/components/case-card/case-card-model.ts
  v3/src/components/case-card/case-card.scss
  v3/src/components/case-card/case-card.tsx
  v3/src/components/case-card/case-view.scss
  v3/src/components/case-tile-common/attribute-menu/attribute-menu.scss
  v3/src/components/case-tile-common/inspector-panel/dataset-info-modal.scss
  v3/src/components/codap-modal.scss
  v3/src/components/common/edit-formula-modal.scss
  v3/src/components/common/formula-insert-menus.scss
  v3/src/components/common/formula-insert-values-menu.tsx
  v3/src/components/component-title-bar.scss
  v3/src/components/container/container.scss
  v3/src/components/container/container.tsx
  v3/src/components/container/free-tile-row.scss
  v3/src/components/data-display/components/attribute-label.scss
  v3/src/components/data-display/components/legend/legend.scss
  v3/src/components/data-display/inspector/display-item-format-control.tsx
  v3/src/components/data-display/inspector/inspector-panel.scss
  v3/src/components/graph/components/graph.scss
  v3/src/components/inspector-panel.scss
  v3/src/components/map/components/map.scss
  v3/src/components/slider/inspector-panel/slider-settings-panel.scss
  v3/src/components/slider/slider.scss
  v3/src/components/tiles/placeholder/placeholder-tile.scss
  v3/src/components/tool-shelf/tool-shelf.scss
  v3/src/components/web-view/web-view.scss
  v3/src/models/formula/lezer/parser.test.ts
Labels: v3, run regression

#1588 Categorical legend and axis respond to order changes
  v3/src/components/data-display/components/legend/categorical-legend.tsx
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/components/casedots.tsx
  v3/src/components/graph/components/dot-chart-bars.tsx
  v3/src/components/graph/components/graph-inspector.tsx
  v3/src/components/graph/hooks/use-graph-model.ts
  v3/src/components/graph/hooks/use-plot.ts
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/models/graph-controller.ts
  v3/src/components/graph/models/graph-data-configuration-model.test.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/components/graph/utilities/dot-plot-utils.ts
  v3/src/components/map/components/map-point-layer.tsx
  v3/src/components/map/components/map-polygon-layer.tsx
  v3/src/components/map/models/map-grid-model.ts
  v3/src/components/map/models/map-point-layer-model.ts
Labels: v3, run regression

#1566 187223531 Restore and Replace setAside API Requests
  v3/src/components/case-tile-common/hide-show-menu-list.tsx
  v3/src/data-interactive/data-interactive-types.ts
  v3/src/data-interactive/handlers/data-context-handler.test.ts
  v3/src/data-interactive/handlers/data-context-handler.ts
  v3/src/models/data/data-set-notifications.ts
  v3/src/models/data/data-set-utils.ts
  v3/src/models/data/data-set.ts
  v3/src/models/history/apply-model-change.ts
Labels: v3, run regression

#1592 Dragging dot plot point bug
  v3/src/components/graph/hooks/use-plot.ts
Labels: v3

#1590 feat: Tab key accepts auto-complete suggestion
  v3/src/components/common/formula-editor.tsx
Labels: v3, run regression

#1596 188476241 API Get Collection Hidden Attributes
  v3/src/data-interactive/handlers/collection-handler.test.ts
  v3/src/data-interactive/handlers/collection-handler.ts
Labels: v3

#1597 staging build 3.0.0-pre.1976
  v3/CHANGELOG.md
  v3/cypress/e2e/axis.spec.ts
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1591 187014862 v3 Point Color for Color Attribute Legend
  v3/cypress/e2e/graph-legend.spec.ts
  v3/cypress/support/helpers/graph-legend-helper.ts
  v3/src/components/data-display/components/legend/categorical-legend.tsx
  v3/src/components/data-display/components/legend/color-legend.tsx
  v3/src/components/data-display/components/legend/legend-common.ts
  v3/src/components/data-display/components/legend/legend.tsx
  v3/src/components/data-display/components/legend/numeric-legend.tsx
  v3/src/components/data-display/models/data-configuration-model.ts
Labels: v3, run regression

#1599 fix: deselect on click on PIXI point
  v3/src/components/data-display/data-display-utils.ts
  v3/src/components/data-display/hooks/use-pixi-pointer-down-deselect.ts
  v3/src/components/data-display/hooks/use-pixi-pointer-down.ts
  v3/src/components/data-display/pixi/pixi-points.ts
Labels: v3, run regression

#1593 feat: implement bivariate aggregate functions
  v3/src/models/formula/functions/aggregate-functions.ts
  v3/src/models/formula/functions/bivariate-stats-functions.test.ts
  v3/src/models/formula/functions/bivariate-stats-functions.ts
  v3/src/models/formula/functions/math.ts
  v3/src/models/formula/functions/univariate-stats-functions.ts
  v3/src/utilities/nist-noint1.ts
  v3/src/utilities/nist-norris.ts
  v3/src/utilities/stats-utils.test.ts
  v3/src/utilities/stats-utils.ts
Labels: v3, run regression

#1601 fix: case table update on exit from performance mode
  v3/src/components/case-table/use-rows.ts
Labels: v3, run regression

#1598 188323297 Allow Domains to Shrink When Rescaling
  v3/src/components/graph/models/graph-content-model.ts
Labels: v3, run regression

#1603 Bring back flaky graph axis test in smoke test spec
  v3/CHANGELOG.md
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/cypress/support/helpers/axis-helper.ts
Labels: v3, run regression

#1594 181910061 Numeric Legend Color Picker
  v3/src/components/data-display/components/legend/numeric-legend.tsx
  v3/src/components/data-display/inspector/display-item-format-control.tsx
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/hooks/use-plot.ts
  v3/src/models/codap/create-codap-document.test.ts
  v3/src/models/shared/shared-case-metadata-constants.ts
  v3/src/models/shared/shared-case-metadata.ts
  v3/src/utilities/color-utils.ts
Labels: v3, run regression

#1602 188411147 rename click away
  v3/cypress/support/commands.ts
  v3/src/components/case-tile-common/attribute-header.tsx
Labels: v3, run regression

#1600 187502179 fix color palette table placement
  v3/src/components/case-table/color-cell-text-editor.tsx
  v3/src/components/common/color-picker-palette.scss
  v3/src/components/common/color-picker-palette.scss.d.ts
  v3/src/components/common/color-picker-palette.tsx
Labels: v3

#1608 fix: hierarchical case table updates while dragging points in a graph
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-table/use-rows.ts
Labels: v3, run regression

#1607 feat: implement bivariate semi-aggregates (linRegrPredicted, linRegrResidual)
  v3/src/models/formula/formula-mathjs-scope.ts
  v3/src/models/formula/functions/bivariate-stats-functions.test.ts
  v3/src/models/formula/functions/bivariate-stats-functions.ts
  v3/src/models/formula/test-utils/formula-test-utils.ts
  v3/src/utilities/stats-utils.ts
Labels: v3, run regression

#1595 Implements resize all columns to fit longest string
  v3/cypress/support/commands.ts
  v3/src/components/case-table/case-table-model.ts
  v3/src/components/case-table/case-table-types.ts
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-tile-common/inspector-panel/case-tile-inspector.tsx
Labels: v3, run regression

#1612 fix: crash in `usePixiPointerDown` due to undefined PixiPoints
  v3/src/components/data-display/components/background.tsx
  v3/src/components/data-display/hooks/use-pixi-pointer-down-deselect.ts
  v3/src/components/data-display/hooks/use-pixi-pointer-down.ts
  v3/src/components/data-display/hooks/use-pixi-points-array.ts
  v3/src/components/data-display/pixi/pixi-points.ts
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/hooks/use-graph-controller.ts
  v3/src/components/map/components/map-background.tsx
Labels: v3, run regression

#1610 Bug where split dot plot messes up when hierarchy changes
  v3/src/components/axis/hooks/use-sub-axis.ts
  v3/src/components/axis/models/multi-scale.ts
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/utilities/graph-utils.ts
Labels: v3, run regression

#1584 Fixes bug where user can drag components under toolshelf
  v3/src/components/container/container-constants.ts
  v3/src/components/container/free-tile-row.tsx
  v3/src/hooks/use-drag-drop.ts
  v3/src/lib/dnd-kit/codap-dnd-context.tsx
Labels: v3, run regression

#1611 Fix for map failure to zoom on open bug
  v3/src/components/map/models/map-content-model.ts
Labels: v3, run regression

#1604 188402995 automation slider with dates
  v3/cypress/e2e/slider.spec.ts
  v3/cypress/support/elements/component-elements.ts
  v3/cypress/support/elements/slider-tile.ts
  v3/src/components/slider/inspector-panel/slider-scales-panel.tsx
  v3/src/components/slider/inspector-panel/slider-settings-panel.tsx
Labels: v3, run regression

#1609 188497532 graph map filter formula editor
  v3/cypress/e2e/adornments.spec.ts
  v3/cypress/support/helpers/formula-helper.ts
  v3/src/components/common/edit-formula-modal.tsx
  v3/src/components/graph/components/inspector-panel/hide-show-menu-list.tsx
  v3/src/components/map/components/inspector-panel/hide-show-menu-list.tsx
  v3/src/hooks/use-inspector-formula-string.ts
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#1614 chore: move eslint-webpack-plugin cache from node_modules/.cache to .cache
  v3/webpack.config.js
Labels: v3

#1618 fix: table row selection and child table scrolling
  v3/src/components/case-table/case-table-types.ts
  v3/src/components/case-table/case-table.tsx
  v3/src/components/case-table/collection-table-model.ts
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-table/use-selected-rows.ts
  v3/src/components/case-table/use-sync-scrolling.ts
Labels: v3, run regression

#1619 use new cfm openLocalFileWithConfirmation
  v3/package-lock.json
  v3/package.json
  v3/src/components/app.tsx
  v3/src/hooks/use-drop-handler.ts
Labels: v3, run regression

#1616 PT-#188560369 Fix Failing Cypress Tests in axis.spec.ts
  v3/cypress/e2e/axis.spec.ts
  v3/cypress/e2e/graph.spec.ts
Labels: v3, run regression

#1622 fix: import of v2 documents with minimized components
  v3/src/models/document/free-tile-row.ts
  v3/src/v2/import-v2-document.ts
Labels: v3, run regression

#1620 182991523 date type precision menu
  v3/src/components/case-table/use-columns.tsx
  v3/src/components/case-table/use-rows.ts
  v3/src/components/case-tile-common/attribute-format-utils.tsx
  v3/src/components/case-tile-common/attribute-menu/edit-attribute-properties-modal.tsx
  v3/src/models/data/attribute-types.ts
  v3/src/models/data/attribute.test.ts
  v3/src/models/data/attribute.ts
Labels: v3, run regression

#1617 188497528 case tile filter formula editor
  v3/cypress/e2e/formula/formula-component.spec.ts
  v3/cypress/e2e/formula/formula-errors.spec.ts
  v3/cypress/e2e/formula/formula-functions.spec.ts
  v3/cypress/e2e/formula/formula-hierarchical-tables.spec.ts
  v3/cypress/e2e/formula/formula-special-characters.spec.ts
  v3/cypress/e2e/table.spec.ts
  v3/cypress/support/elements/slider-tile.ts
  v3/cypress/support/elements/table-tile.ts
  v3/cypress/support/helpers/formula-helper.ts
  v3/src/components/case-tile-common/hide-show-menu-list.tsx
  v3/src/components/common/edit-filter-formula-modal.tsx
Labels: v3, run regression

#1623 Does not list hidden attributes in graph axis menu
  v3/src/components/axis/components/axis-or-legend-attribute-menu.tsx
Labels: v3, run regression

#1627 try using setup-chrome
  .github/workflows/v3-regression.yml
  .github/workflows/v3.yml
Labels: run regression

#1621 Right justifies numeric types and changes font to a monspaced font
  v3/cypress/e2e/graph-legend.spec.ts
  v3/cypress/support/helpers/color-helper.ts
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-tile-common/attribute-format-utils.tsx
  v3/src/index.html
Labels: v3, run regression

#1628 staging build 3.0.0-pre.2009
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1626 fix: bivariate semi-aggregates (linRegrPredicted, linRegrResidual) respect filter argument
  v3/src/models/formula/functions/bivariate-stats-functions.ts
Labels: v3

#1630 fix: handling of hidden/minimized tiles
  v3/src/models/document/free-tile-row.ts
  v3/src/v2/import-v2-document.ts
Labels: v3, run regression

#1624 update window title when the document name changes
  v3/cypress/e2e/cfm.spec.ts
  v3/src/components/tool-shelf/tool-shelf.test.tsx
  v3/src/lib/handle-cfm-event.ts
  v3/src/lib/logger.ts
  v3/src/models/app-state.ts
  v3/src/models/codap/create-codap-document.ts
  v3/src/models/document/document.test.ts
  v3/src/models/document/document.ts
  v3/src/v2/import-v2-document.ts
Labels: v3, run regression

#1613 187849414 Autodetect Boundary Type
  v3/cypress/e2e/table.spec.ts
  v3/cypress/support/elements/table-tile.ts
  v3/src/boundaries/US_State_Boundaries.json
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-tile-common/attribute-format-utils.tsx
  v3/src/components/map/map-types.ts
  v3/src/components/map/utilities/map-utils.ts
  v3/src/models/data/attribute.ts
  v3/src/models/formula/functions/lookup-functions.test.ts
  v3/src/models/formula/functions/lookup-functions.ts
  v3/src/models/formula/utils/formula-dependency-utils.test.ts
  v3/src/models/formula/utils/formula-dependency-utils.ts
  v3/src/models/formula/utils/name-mapping-utils.test.ts
  v3/src/models/formula/utils/name-mapping-utils.ts
  v3/src/utilities/boundary-utils.test.ts
  v3/src/utilities/boundary-utils.ts
Labels: v3, run regression

#1629 fix: don't show date precision options if user has chosen another type
  v3/src/components/case-tile-common/attribute-menu/edit-attribute-properties-modal.tsx
Labels: v3, run regression

#1641 Fix: case card has notifications when collections move (PT-188571448)
  v3/src/components/case-card/case-card.tsx
Labels: v3, run regression

#1638 188392104 case card formula
  v3/src/components/case-card/case-attr-view.tsx
  v3/src/components/case-card/case-attrs-view.tsx
  v3/src/components/case-card/case-card-model.ts
  v3/src/components/case-table/attribute-value-cell.tsx
  v3/src/components/case-table/use-rows.ts
  v3/src/components/case-tile-common/attribute-format-utils.tsx
  v3/src/components/case-tile-common/attribute-menu/edit-attribute-properties-modal.tsx
Labels: v3, run regression

#1642 Detect lat/lng attribute names independent of case
  v3/src/components/map/utilities/map-utils.ts
Labels: v3

#1637 SPIKE: Integrate Cypress with PixiJS
  v3/cypress/e2e/graph.spec.ts
  v3/cypress/support/commands.ts
Labels: v3, run regression

#1644 Update autoscale cypress test with comments and reference to known issue
  v3/cypress/e2e/graph.spec.ts
Labels: v3

#1647 staging build 3.0.0-pre.2023
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1645 handle CFM sharing data
  v3/README.md
  v3/src/lib/debug.ts
  v3/src/lib/handle-cfm-event.test.ts
  v3/src/lib/handle-cfm-event.ts
Labels: run regression

#1651 chore: disable slow graph cypress test
  v3/cypress/e2e/graph.spec.ts
Labels: v3, run regression

#1635 188544725 v3 Remote Boundaries
  v3/src/boundaries/US_State_Boundaries.json
  v3/src/components/case-tile-common/attribute-format-utils.tsx
  v3/src/components/common/formula-editor.tsx
  v3/src/components/common/formula-insert-values-menu.tsx
  v3/src/components/graph/adornments/plotted-function/plotted-function-formula-adapter.test.ts
  v3/src/components/graph/adornments/univariate-measures/plotted-value/plotted-value-formula-adapter.test.ts
  v3/src/components/map/utilities/map-utils.ts
  v3/src/components/web-view/web-view-utils.ts
  v3/src/constants.ts
  v3/src/hooks/use-remote-plugins-config.test.ts
  v3/src/lib/use-cloud-file-manager.ts
  v3/src/models/boundaries/boundary-manager.test.ts
  v3/src/models/boundaries/boundary-manager.ts
  v3/src/models/boundaries/boundary-types.test.ts
  v3/src/models/boundaries/boundary-types.ts
  v3/src/models/data/attribute.ts
  v3/src/models/formula/attribute-formula-adapter.test.ts
  v3/src/models/formula/attribute-formula-adapter.ts
  v3/src/models/formula/filter-formula-adapter.test.ts
  v3/src/models/formula/formula-manager-types.ts
  v3/src/models/formula/formula-manager.test.ts
  v3/src/models/formula/formula-manager.ts
  v3/src/models/formula/formula-mathjs-scope.ts
  v3/src/models/formula/formula-observers.ts
  v3/src/models/formula/formula-types.ts
  v3/src/models/formula/functions/lookup-functions.test.ts
  v3/src/models/formula/functions/lookup-functions.ts
  v3/src/models/formula/lezer/formula-highlight.scss
  v3/src/models/formula/test-utils/formula-test-utils.ts
  v3/src/models/formula/utils/name-mapping-utils.ts
  v3/src/utilities/boundary-utils.ts
Labels: v3, run regression

#1650 fix: ruler menu re-renders on undo collection change
  v3/src/components/case-tile-common/inspector-panel/ruler-menu-list.tsx
Labels: v3, run regression

#1639 Changes min width for auto rescale
  v3/src/components/case-table/case-table-types.ts
  v3/src/components/case-tile-common/attribute-format-utils.tsx
  v3/src/components/case-tile-common/attribute-menu/attribute-menu-list.tsx
  v3/src/components/case-tile-common/inspector-panel/case-tile-inspector.tsx
Labels: v3, run regression

#1654 fix: preserve case and item ids on import of v2 document
  v3/src/components/case-table/use-index-column.tsx
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/lib/debug.ts
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-import.test.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1655 Fix for bug in which splitting on top and right not working properly
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/models/graph-controller.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
Labels: v3, run regression

#1649 188514789 case card color picker
  v3/cypress/e2e/case-card.spec.ts
  v3/cypress/e2e/table.spec.ts
  v3/src/components/case-card/case-attr-view.scss
  v3/src/components/case-card/case-attr-view.tsx
  v3/src/components/case-card/case-attrs-view.tsx
  v3/src/components/case-table/color-cell-text-editor.tsx
  v3/src/components/case-tile-common/color-text-editor.scss
  v3/src/components/case-tile-common/color-text-editor.tsx
  v3/src/components/common/color-picker-palette.tsx
Labels: v3, run regression

#1652 Changes the cursor for the input line to text
  v3/src/components/case-table/case-table.scss
Labels: v3, run regression

#1657 Turn off animation for map points
  v3/src/components/map/components/map-point-layer.tsx
Labels: v3, run regression

#1656 feat: support DEBUG_CFM_NO_AUTO_SAVE debug option to disable auto-save
  v3/README.md
  v3/src/lib/debug.ts
  v3/src/lib/use-cloud-file-manager.ts
Labels: v3

#1660 Fix for numeric axis resize & rescale bug
  v3/src/components/axis/helper-models/numeric-axis-helper.ts
Labels: v3, run regression
