Repository concord-consortium/codap, pull requests merged in 2024-12, with the labels that each got.

#1658 improve adornment v2 importer typing
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/adornments/adornment-models.ts
  v3/src/components/graph/adornments/adornment-types.ts
  v3/src/components/graph/adornments/adornment-utils.ts
  v3/src/components/graph/adornments/count/count-adornment-model.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.ts
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-model.ts
  v3/src/components/graph/adornments/movable-point/movable-point-adornment-model.ts
  v3/src/components/graph/adornments/movable-value/movable-value-adornment-model.ts
  v3/src/components/graph/adornments/plotted-function/plotted-function-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/mean-absolute-deviation/mean-absolute-deviation-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/mean/mean-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/median/median-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/plotted-value/plotted-value-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/standard-deviation/standard-deviation-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/standard-error/standard-error-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-model.ts
  v3/src/components/graph/adornments/v2-adornment-importer.test.ts
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/v2-graph-importer.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1659 fix: import of v2 documents with maps
  v3/src/components/map/map-model-types.ts
  v3/src/components/map/models/map-content-model.ts
  v3/src/components/map/v2-map-importer.test.ts
  v3/src/components/map/v2-map-importer.ts
  v3/src/test/v2/roller-coasters-map.codap
  v3/src/test/v2/seal-and-shark-demo.codap
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1663 Restore dynamic update of mean adornment
  v3/src/components/data-display/models/data-configuration-model.ts
Labels: v3

#1646 Added back graph rescale Cypress test
  v3/cypress/e2e/graph.spec.ts
Labels: v3, run regression

#1665 feat: v2 export infrastructure
  v3/src/components/calculator/calculator-defs.ts
  v3/src/components/calculator/calculator-registration.test.ts
  v3/src/components/calculator/calculator-registration.ts
  v3/src/data-interactive/data-interactive-component-types.ts
  v3/src/lib/config.ts
  v3/src/lib/debug.ts
  v3/src/lib/use-cloud-file-manager.ts
  v3/src/models/app-state.test.ts
  v3/src/models/app-state.ts
  v3/src/models/codap/create-codap-document.ts
  v3/src/v2/codap-v2-import.test.ts
  v3/src/v2/codap-v2-tile-exporters.ts
  v3/src/v2/codap-v2-types.ts
  v3/src/v2/export-v2-document.test.ts
  v3/src/v2/export-v2-document.ts
Labels: v3, run regression

#1674 fix: handling of set-aside cases in imported/restored documents
  v3/src/data-interactive/data-interactive-type-utils.ts
  v3/src/data-interactive/data-interactive-types.ts
  v3/src/models/data/collection.ts
  v3/src/models/data/data-set-conversion.test.ts
  v3/src/models/data/data-set.ts
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1653 188618452 new table clean up
  v3/cypress/e2e/formula/formula-component.spec.ts
  v3/cypress/e2e/plugin.spec.ts
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/cypress/support/elements/table-tile.ts
  v3/src/components/case-table/case-table-registration.ts
  v3/src/components/case-table/case-table-tool-shelf-button.tsx
  v3/src/components/case-table/case-table-types.ts
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-table/case-table.tsx
  v3/src/components/case-table/use-rows.ts
  v3/src/components/case-tile-common/case-tile-utils.ts
  v3/src/models/document/document-content.ts
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#1677 staging build 3.0.0-pre.2046
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3

#1678 chore: eslint v9 upgrade [PT-187950465]
  v3/.eslintrc.build.cjs
  v3/.eslintrc.cjs
  v3/.eslintrc.style.cjs
  v3/eslint.build.config.mjs
  v3/eslint.config.mjs
  v3/package-lock.json
  v3/package.json
  v3/src/components/case-card/case-card.tsx
  v3/src/components/graph/components/droppable-plot.tsx
  v3/src/components/graph/hooks/use-init-graph-layout.ts
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/map/components/map-point-grid.tsx
  v3/src/components/map/map-registration.ts
  v3/src/components/slider/slider-thumb.tsx
  v3/src/components/text/text-tile.tsx
  v3/src/hooks/use-drag-drop.ts
  v3/src/models/data/attribute.ts
  v3/tsconfig.json
  v3/webpack.config.js
Labels: v3, run regression

#1662 Update the types to match some docs in cfm-shared
  v3/scripts/v2-support/package-lock.json
  v3/scripts/v2-support/package.json
  v3/scripts/v2-support/v2-schema.json
  v3/scripts/v2-support/validate-files.sh
  v3/scripts/v2-support/validate-results.sh
  v3/src/components/calculator/calculator-registration.test.ts
  v3/src/components/calculator/calculator-registration.ts
  v3/src/components/case-table/case-table-registration.ts
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/v2-graph-importer.test.ts
  v3/src/components/graph/v2-graph-importer.ts
  v3/src/components/map/v2-map-importer.test.ts
  v3/src/components/map/v2-map-importer.ts
  v3/src/components/slider/slider-registration.ts
  v3/src/components/web-view/web-view-registration.ts
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-import.test.ts
  v3/src/v2/codap-v2-tile-exporters.ts
  v3/src/v2/codap-v2-types.ts
  v3/src/v2/import-v2-document.ts
Labels: v3, run regression

#1681 188605717 Add Buffer Space to Bar Charts
  v3/src/components/graph/components/freedotplotdots.tsx
Labels: v3, run regression

#1675 188646708 v3 Update Graph API
  v3/src/components/graph/component-handler-graph.test.ts
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/graph-component-handler.ts
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/data-interactive/data-interactive-component-types.ts
  v3/src/data-interactive/handlers/attribute-handler.test.ts
  v3/src/data-interactive/handlers/attribute-location-handler.test.ts
  v3/src/data-interactive/handlers/collection-handler.test.ts
  v3/src/data-interactive/handlers/handler-test-utils.ts
  v3/src/data-interactive/handlers/item-by-case-id-handler.test.ts
  v3/src/data-interactive/handlers/item-by-id-handler.test.ts
  v3/src/data-interactive/handlers/item-handler.test.ts
Labels: v3, run regression

#1679 chore: enhance attribute value types
  v3/src/components/axis/components/axis-or-legend-attribute-menu.tsx
  v3/src/components/case-tile-common/attribute-menu/edit-attribute-properties-modal.tsx
  v3/src/components/data-display/components/attribute-label.tsx
  v3/src/components/data-display/components/legend/legend-attribute-label.tsx
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/components/graph-attribute-label.tsx
  v3/src/components/graph/components/graph-axis.tsx
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/data-interactive/data-interactive-types.ts
  v3/src/data-interactive/handlers/di-handler-utils.ts
  v3/src/hooks/use-drop-hint-string.test.ts
  v3/src/hooks/use-drop-hint-string.ts
  v3/src/models/data/attribute-types.ts
  v3/src/models/data/attribute.test.ts
  v3/src/models/data/attribute.ts
  v3/src/models/data/data-set.ts
  v3/src/models/formula/formula-types.ts
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1680 feat: v2 export of DataSets and globalValues
  v3/src/data-interactive/data-interactive-type-utils.ts
  v3/src/data-interactive/handlers/all-cases-handler.test.ts
  v3/src/data-interactive/handlers/case-handler.test.ts
  v3/src/data-interactive/handlers/collection-handler.ts
  v3/src/data-interactive/handlers/data-context-handler.ts
  v3/src/models/data/attribute.test.ts
  v3/src/models/data/attribute.ts
  v3/src/models/data/data-set-collections.test.ts
  v3/src/models/data/data-set.test.ts
  v3/src/models/data/data-set.ts
  v3/src/models/formula/attribute-formula-adapter.test.ts
  v3/src/models/formula/functions/lookup-functions.test.ts
  v3/src/models/formula/functions/semi-aggregate-functions.test.ts
  v3/src/models/formula/functions/string-functions.ts
  v3/src/models/formula/test-utils/formula-test-utils.test.ts
  v3/src/v2/codap-v2-types.ts
  v3/src/v2/export-v2-document.test.ts
  v3/src/v2/export-v2-document.ts
Labels: v3, run regression

#1682 handle all properties defined in a sample of 6,000 files from cfm-shared
  v3/scripts/v2-support/v2-schema.json
  v3/src/components/graph/v2-graph-importer.ts
  v3/src/components/map/v2-map-importer.ts
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-types.ts
Labels: run regression

#1684 feat: export case table in v2 format
  v3/src/components/case-table/case-table-registration.test.ts
  v3/src/components/case-table/case-table-registration.ts
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-tile-exporters.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1683 188651851 v3 DI Multiple Y Attributes
  v3/src/components/graph/component-handler-graph.test.ts
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/graph-component-handler.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/data-interactive/data-interactive-component-types.ts
Labels: v3, run regression

#1687 staging branch 3.0.0-pre.2058
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1685 Fix graph binWidth computation to avoid crash
  v3/src/components/graph/adornments/count/count-adornment-component.tsx
  v3/src/components/graph/components/binneddotplotdots.tsx
  v3/src/components/graph/components/histogram.tsx
  v3/src/components/graph/hooks/use-dot-plot.ts
  v3/src/components/graph/models/graph-content-model.ts
Labels: v3, run regression

#1686 188651857 v3 DI Top Level Graph Features
  v3/src/components/graph/component-handler-graph.test.ts
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/graph-component-handler.ts
  v3/src/data-interactive/data-interactive-component-types.ts
Labels: v3, run regression

#1688 export WebView in v2 documents
  v3/src/components/web-view/web-view-registration.test.ts
  v3/src/components/web-view/web-view-registration.ts
  v3/src/test/v2/web-view-image.codap
  v3/src/v2/codap-v2-tile-exporters.ts
Labels: v3, run regression

#1691 feat: import/export case card from/to v2 documents
  v3/src/components/case-card/case-card-model.ts
  v3/src/components/case-card/case-card-registration.test.ts
  v3/src/components/case-card/case-card-registration.ts
  v3/src/components/case-table/case-table-registration.ts
  v3/src/data-interactive/data-interactive-type-utils.ts
  v3/src/test/v2/mammals-case-card.codap
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-tile-importers.ts
  v3/src/v2/codap-v2-types.ts
  v3/src/v2/import-v2-document.ts
Labels: v3, run regression

#1695 feat: v2 slider export
  v3/src/components/slider/slider-model.ts
  v3/src/components/slider/slider-registration.test.ts
  v3/src/components/slider/slider-registration.ts
  v3/src/components/slider/slider-types.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1690 Export game view
  v3/src/components/web-view/component-handler-web-view.test.ts
  v3/src/components/web-view/use-data-interactive-controller.ts
  v3/src/components/web-view/web-view-defs.ts
  v3/src/components/web-view/web-view-model.ts
  v3/src/components/web-view/web-view-registration.test.ts
  v3/src/components/web-view/web-view-registration.ts
  v3/src/data-interactive/data-interactive-type-utils.ts
  v3/src/test/v2/game-view-microdata.codap
  v3/src/v2/codap-v2-tile-exporters.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1696 188651857 Fix update graph displayOnlySelectedCases.
  v3/src/components/graph/components/inspector-panel/hide-show-menu-list.tsx
  v3/src/components/graph/graph-component-handler.test.ts
  v3/src/components/graph/graph-component-handler.ts
  v3/src/components/graph/models/graph-content-model.ts
Labels: v3, run regression

#1701 fix: v2 export of hierarchical Dataset
  v3/src/data-interactive/data-interactive-type-utils.test.ts
  v3/src/data-interactive/data-interactive-type-utils.ts
Labels: v3, run regression

#1702 fix: lookup functions match user-set title
  v3/src/models/formula/utils/name-mapping-utils.ts
Labels: v3, run regression

#1700 181846570 adjustable row height
  v3/cypress/support/elements/table-tile.ts
  v3/src/components/case-table/attribute-value-cell.tsx
  v3/src/components/case-table/case-table-model.ts
  v3/src/components/case-table/case-table-shared.scss
  v3/src/components/case-table/case-table-types.ts
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-table/collection-table-model.ts
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-table/row-divider.tsx
  v3/src/components/case-table/use-columns.tsx
  v3/src/components/case-table/use-index-column.tsx
  v3/src/components/case-table/use-rows.ts
  v3/src/components/case-tile-common/attribute-format-utils.tsx
Labels: v3, run regression

#1703 staging build 3.0.0-pre.2068
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1705 fix: v2 slider export
  v3/src/components/slider/slider-registration.test.ts
  v3/src/components/slider/slider-registration.ts
Labels: v3, run regression

#1689 188527686 formula editor improvements
  v3/src/components/codap-modal.scss
  v3/src/components/codap-modal.tsx
  v3/src/components/common/edit-formula-modal.scss
  v3/src/components/common/edit-formula-modal.scss.d.ts
  v3/src/components/common/edit-formula-modal.tsx
  v3/src/components/common/formula-editor.tsx
Labels: v3, run regression

#1704 Scrolls child cases into view on keyboard selection
  v3/src/components/case-table/collection-table.tsx
Labels: v3, run regression

#1694 Update some TODO_V2_IMPORT comments
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/v2-graph-importer.ts
  v3/src/components/map/v2-map-importer.ts
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3

#1698 async api handlers
  v3/src/components/web-view/request-queue.ts
  v3/src/components/web-view/use-data-interactive-controller.ts
  v3/src/data-interactive/data-interactive-handler.ts
  v3/src/data-interactive/data-interactive-types.ts
Labels: v3, run regression

#1693 add dataContextFromURL api
  v3/src/data-interactive/data-interactive-types.ts
  v3/src/data-interactive/handlers/data-context-from-url-handler.test.ts
  v3/src/data-interactive/handlers/data-context-from-url-handler.ts
  v3/src/models/app-state.ts
  v3/src/sample-data/index.ts
  v3/src/utilities/csv-import.ts
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#1699 switch dataContextFromURL to be async
  v3/src/data-interactive/handlers/data-context-from-url-handler.test.ts
  v3/src/data-interactive/handlers/data-context-from-url-handler.ts
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression
