Repository concord-consortium/codap, pull requests merged in 2025-08, with the labels that each got.

#2071 fix: case names for collapsed cases in table [CODAP-363]
  v3/cypress/fixtures/hierarchical.json
  v3/src/components/app.tsx
  v3/src/components/case-table/use-index-column.tsx
  v3/src/models/data/data-set-utils.test.ts
  v3/src/models/data/data-set-utils.ts
  v3/src/models/document/document-content.ts
Labels: v3, run regression

#2074 CODAP-829 Make Rescale work for histogram
  v3/src/components/graph/plots/histogram/histogram-model.ts
Labels: v3, run regression

#2077 Codap-830 Tile Restyle
  v3/cypress/e2e/graph.spec.ts
  v3/cypress/e2e/pixi-interaction/graph-pixi-interaction.spec.ts
  v3/cypress/e2e/tool-shelf.spec.ts
  v3/cypress/support/elements/component-elements.ts
  v3/cypress/support/elements/table-tile.ts
  v3/src/assets/icons/icon-case-card.svg
  v3/src/assets/icons/icon-corner-resize-handle.svg
  v3/src/components/axis/components/axis-or-legend-attribute-menu.scss
  v3/src/components/case-tile-common/case-tile-title-bar.scss
  v3/src/components/case-tile-common/case-tile-title-bar.tsx
  v3/src/components/codap-component.scss
  v3/src/components/codap-component.tsx
  v3/src/components/common/edit-formula-modal.scss
  v3/src/components/component-title-bar.scss
  v3/src/components/component-title-bar.tsx
  v3/src/components/constants.ts
  v3/src/components/container/component-resize-widgets.tsx
  v3/src/components/container/free-tile-component.tsx
  v3/src/components/inspector-panel.scss
  v3/src/components/tool-shelf/tool-shelf.scss
  v3/src/components/tool-shelf/tool-shelf.tsx
  v3/src/components/vars.scss
  v3/src/data-interactive/handlers/interactive-frame-handler.test.ts
Labels: v3, run regression

#2079 chore: project review tweak [CODAP-824]
  v3/src/components/case-table/use-index-column.tsx
Labels: v3, run regression

#2080 CODAP 816 Use V2 document background
  v3/src/components/container/container.scss
Labels: v3

#2081 CODAP-833 Failure to swap scatterplot axes properly
  v3/src/components/graph/hooks/use-plot.ts
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/models/graph-model-utils.ts
Labels: v3

#2085 Build 0739 -- add French and Dutch translations
  .codap-data-interactives_githash
  .codap-data_githash
  .story-builder_githash
  apps/dg/core.js
  apps/dg/fr.lproj/strings.js
  apps/dg/nl.lproj/strings.js
  apps/dg/resources/cloud-file-manager/css/app.css
  apps/dg/resources/cloud-file-manager/js/app.js.ignore
  apps/dg/tr.lproj/strings.js
  bin/do-full-build-process
  bin/strings-pull-project.sh
  cfm-version.txt
  docs/formal-build-process.md
Labels: v2

#2088 chore: still more build 0739 tweaks
  .codap-data-interactives_githash
Labels: v2

#2082 CODAP-841 Fix to allow graph/map attribute menus to render outside component boundaries
  v3/src/components/codap-component.scss
Labels: v3, run regression

#2084 CODAP-43 Getting Story Builder to work in V3
  v3/src/components/tool-shelf/standard-plugins.json
  v3/src/components/web-view/web-view-model.ts
  v3/src/data-interactive/data-interactive-types.ts
  v3/src/data-interactive/handlers/component-handler.ts
  v3/src/data-interactive/handlers/document-handler.ts
  v3/src/data-interactive/handlers/interactive-frame-handler.ts
  v3/src/data-interactive/register-handlers.ts
  v3/src/models/data/attribute.ts
  v3/src/models/document/serialize-document.ts
  v3/src/models/global/global-value-manager.ts
Labels: v3

#2093 CODAP-862 Fix for movable line causing invalid document
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-model.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/components/graph/utilities/graph-utils.ts
Labels: v3

#2091 chore: update meta description content
  v3/src/index.html
Labels: v3

#2097 CODAP-850 Edit text should notify
  v3/src/components/text/text-tile.tsx
Labels: v3, run regression

#2104 CODAP-874 Fix dynamic response of LSRL
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-component.tsx
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.ts
  v3/src/components/graph/plots/dot-plot/dot-line-plot.tsx
Labels: v3

#2105 CODAP-885 Miscomputation of LSRL
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.ts
Labels: v3, run regression
