Repository concord-consortium/codap, pull requests merged in 2025-05, with the labels that each got.

#1929 feat: add deployment link to Jira (START-1)
  .github/workflows/v3.yml
Labels: run regression

#1932 CODAP-366-Fix parent toggles crash
  v3/src/components/graph/components/parent-toggles.tsx
Labels: v3, run regression

#1930 Adds tile name, and rescaleAxes to graph component handler
  v3/src/components/data-display/hooks/use-connecting-lines.ts
  v3/src/data-interactive/handlers/component-handler.ts
Labels: v3, run regression

#1934 CODAP-660 Fix binned dot plot display
  v3/src/components/graph/plots/binned-dot-plot/binned-dot-plot.tsx
Labels: v3

#1935 CODAP-97 Case plots response to change in number of cases bug fix
  v3/src/components/graph/hooks/use-plot.ts
  v3/src/components/graph/plots/case-plot/case-plot.tsx
Labels: v3, run regression

#1931 CODAP-654 Fixes for various graph undo/redo problems
  v3/README.md
  v3/src/components/graph/adornments/line-label-instance.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-component.tsx
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.test.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-registration.tsx
  v3/src/components/graph/adornments/store/adornments-base-store.ts
  v3/src/components/graph/adornments/store/adornments-store-utils.ts
  v3/src/components/graph/adornments/store/adornments-store.test.ts
  v3/src/components/graph/adornments/store/adornments-store.ts
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/components/inspector-panel/graph-measure-palette.tsx
Labels: v3, run regression

#1937 CODAP-654 Changes made in response to review
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-component.tsx
  v3/src/components/graph/adornments/store/adornments-store.test.ts
Labels: v3

#1938 staging build 3.0.0-pre.2293
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1928 Georaster support in CODAP map
  v3/cypress/e2e/map.spec.ts
  v3/cypress/support/elements/map-tile.ts
  v3/doc/georasters.md
  v3/package-lock.json
  v3/package.json
  v3/src/components/map/components/map-interior.tsx
  v3/src/components/map/map-component-handler.ts
  v3/src/components/map/models/map-content-model.ts
  v3/src/components/map/utilities/geo-extent.test.ts
  v3/src/components/map/utilities/geo-extent.ts
  v3/src/components/map/utilities/geo-image.ts
  v3/src/components/map/utilities/georaster-layer-for-leaflet-license.txt
  v3/src/components/map/utilities/georaster-layer-for-leaflet.ts
  v3/src/components/map/utilities/georaster-types/declarations.d.ts
  v3/src/components/map/utilities/georaster-types/index.ts
  v3/src/components/map/utilities/georaster-utils.ts
  v3/src/data-interactive/data-interactive-component-types.ts
Labels: v3, run regression

#1942 CODAP 671 Fixes failing slider CI test.
  v3/cypress/e2e/slider.spec.ts
Labels: v3, run regression

#1939 CODAP-51 Restriction of "percent" option in graph ruler menu
  v3/src/components/graph/adornments/count/count-adornment-registration.tsx
  v3/src/components/graph/models/graph-data-configuration-model.ts
Labels: v3, run regression

#1940 CODAP-136 Get the normal curve adornment to respond dynamically to point dragging
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-component.tsx
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-base-component.scss
Labels: v3, run regression

#1941 Makes table filter formula behave similar to graph plotted function
  v3/src/components/case-tile-common/filter-formula-bar.scss
  v3/src/components/case-tile-common/filter-formula-bar.tsx
Labels: v3, run regression

#1944 CODAP-301 Prevent point dragging if attribute has formula
  v3/src/components/data-display/pixi/pixi-points.ts
  v3/src/components/graph/hooks/use-dot-plot-drag-drop.ts
  v3/src/components/graph/plots/scatter-plot/scatter-plot.tsx
Labels: v3, run regression

#1946 CODAP-672 normalize pin longitude
  v3/cypress/e2e/map.spec.ts
  v3/cypress/support/elements/component-elements.ts
  v3/src/components/map/components/map-pin-layer.tsx
Labels: v3, run regression

#1945 Categorical legend selection sends notification to plugin
  v3/src/components/data-display/components/legend/categorical-legend.tsx
Labels: v3, run regression

#1943 CODAP-670 Box plot responds dynamically to point drag
  v3/src/components/graph/adornments/store/adornments-base-store.ts
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-component.tsx
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-handler.test.ts
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-handler.ts
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-component.tsx
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-model.ts
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/components/graph/plots/binned-dot-plot/binned-dot-plot-model.ts
  v3/src/components/graph/plots/dot-plot/dot-plot-model.ts
  v3/src/components/graph/plots/histogram/histogram-model.ts
  v3/src/components/graph/plots/line-plot/line-plot-model.ts
  v3/src/components/graph/plots/plot-model.ts
Labels: v3, run regression

#1947 staging build 3.0.0-pre.2304
  v3/CHANGELOG.md
  v3/cypress/e2e/slider.spec.ts
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: run regression

#1948 CODAP-658 Caption should not be a hidden attribute
  v3/src/components/data-display/models/data-configuration-model.ts
Labels: v3

#1950 CODAP-364 No data tips when pointer is down
  v3/src/components/data-display/models/pointer-state.ts
  v3/src/components/data-display/pixi/pixi-points.ts
  v3/src/components/graph/adornments/movable-point/movable-point-adornment-component.tsx
Labels: v3

#1951 CODAP-112 Don't show data tips when something else is on top
  v3/src/components/data-display/pixi/pixi-points.ts
Labels: v3

#1949 CODAP-674-Investigate-and-fix-date-slider-spec
  v3/cypress/e2e/slider.spec.ts
  v3/cypress/support/elements/slider-tile.ts
Labels: run regression

#1952 CODAP-111 Show attribute description on graph axis label hover
  v3/src/components/axis/components/axis-or-legend-attribute-menu.tsx
Labels: v3, run regression

#1953 CODAP-678 Rescale with >1 y-axis attributes problems
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/graph-component-handler.test.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/components/graph/models/graph-model-utils.ts
Labels: v3, run regression

#1954 CODAP-679 Numeric graph y-axis not adjusting layout when scale changes
  v3/src/components/axis/hooks/use-axis.ts
Labels: v3, run regression

#1956 CODAP-99 Improved handling of attribute menu for date attribute
  v3/src/components/axis/components/axis-or-legend-attribute-menu.tsx
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#1959 CODAP-111 Fix for remaining problem from prior PR showing attribute description on hover over axis or legend label
  v3/src/components/axis/components/axis-or-legend-attribute-menu.tsx
Labels: v3, run regression

#1955 CLUE-133 add some documentation on the formula system
  v3/doc/formulas.md
Labels: v3

#1964 staging build 3.0.0-pre.2316
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1958 CODAP-680 Prevent overlap of y-axis numeric axis numbers
  v3/src/components/axis/axis-utils.ts
  v3/src/components/axis/helper-models/numeric-axis-helper.ts
Labels: v3, run regression
