Repository concord-consortium/codap, pull requests merged in 2025-07, with the labels that each got.

#2005 Codap-696 Export Graphs as SVG
  v3/src/components/data-display/models/data-display-render-state.ts
  v3/src/components/graph/components/camera-menu-list.tsx
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/graph/utilities/image-utils.ts
Labels: v3, run regression

#2006 Improve performance with sampler plugin [CODAP-36]
  v3/src/components/case-table/collection-table-spacer.tsx
  v3/src/hooks/use-adjust-header-overflow.ts
  v3/src/models/data/collection.test.ts
  v3/src/models/data/collection.ts
Labels: v3, run regression

#2009 CODAP-621 Convert % to mod in formulas
  v3/src/models/formula/utils/canonicalization-utils.test.ts
  v3/src/models/formula/utils/canonicalization-utils.ts
Labels: v3, run regression

#2008 CODAP-725 Make DI Formula Engine Handler use Codap Custom Functions
  v3/src/data-interactive/handlers/formula-engine-handler.test.ts
  v3/src/data-interactive/handlers/formula-engine-handler.ts
Labels: v3, run regression

#2011 Codap-723 Case Card Improvements
  v3/cypress/e2e/case-card.spec.ts
  v3/cypress/support/elements/card-tile.ts
  v3/src/components/case-card/case-attr-view.scss
  v3/src/components/case-card/case-attr-view.tsx
  v3/src/components/case-card/case-attrs-view.tsx
  v3/src/components/case-card/case-card-header.tsx
  v3/src/components/case-card/case-view.tsx
  v3/src/components/case-table/column-header.tsx
  v3/src/components/case-tile-common/attribute-header-divider.tsx
  v3/src/components/case-tile-common/attribute-header.tsx
  v3/src/components/drag-drop/attribute-drag-overlay.tsx
  v3/src/hooks/use-drag-drop.ts
Labels: v3, run regression

#2012 fix: unnecessary auto-scroll on cell click [CODAP-688]
  v3/src/components/app.tsx
  v3/src/components/case-table/collection-table.tsx
Labels: v3, run regression

#2013 CODAP-724 Fix Empty Case Card Bug
  v3/src/components/case-card/case-attr-view.tsx
Labels: v3, run regression

#2015 fix: formulas with first() and last() when items are sorted [CODAP-765]
  v3/src/models/data/data-set.ts
  v3/src/models/formula/formula-observers.test.ts
  v3/src/models/formula/formula-observers.ts
Labels: v3, run regression

#2016 Codap-98 Axis Menus with Multiple Collections
  v3/cypress/e2e/axis.spec.ts
  v3/cypress/e2e/pixi-interaction/graph-pixi-interaction.spec.ts
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/cypress/support/helpers/axis-helper.ts
  v3/cypress/support/helpers/graph-canvas-helper.ts
  v3/src/assets/icons/arrow-right.svg
  v3/src/components/axis/components/axis-or-legend-attribute-menu.scss
  v3/src/components/axis/components/axis-or-legend-attribute-menu.tsx
Labels: v3, run regression

#2020 CODAP-769 Improve category drag animation
  v3/src/components/data-display/models/data-display-content-model.ts
  v3/src/components/data-display/pixi/pixi-points.ts
  v3/src/components/graph/hooks/use-plot.ts
Labels: v3, run regression

#2017 CODAP-741 Fix axis layout problems
  v3/cypress/e2e/pixi-interaction/graph-pixi-interaction.spec.ts
  v3/src/components/axis/axis-utils.ts
  v3/src/components/axis/hooks/use-axis.ts
Labels: v3, run regression

#2031 chore: update release instructions in README and fix typo in CHANGELOG
  v3/CHANGELOG.md
  v3/README.md
Labels: v3

#2033 Codap-691 FireFox Plotted Function
  v3/src/components/graph/adornments/plotted-function/plotted-function-adornment-component.tsx
  v3/src/components/graph/utilities/graph-utils.ts
  v3/src/models/formula/formula-manager.ts
Labels: v3, run regression

#2035 Pre-process group keys [CODAP-795]
  v3/src/models/data/collection.ts
Labels: v3, run regression

#2036 fix: Getting Started with CODAP 2 example document
  v3/src/components/web-view/web-view-utils.test.ts
  v3/src/components/web-view/web-view-utils.ts
Labels: v3, run regression

#2039 Codap 118 case table font restyle
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-table/cell-text-editor.tsx
  v3/src/components/vars.scss
  v3/src/index.html
Labels: v3, run regression

#2030 CODAP-46 add unhandled error dialog
  v3/doc/react-render-errors.md
  v3/package-lock.json
  v3/package.json
  v3/src/assets/icons/icon-error-tester.svg
  v3/src/components/app.scss
  v3/src/components/app.tsx
  v3/src/components/error-tester/error-tester-defs.ts
  v3/src/components/error-tester/error-tester-model.ts
  v3/src/components/error-tester/error-tester-registration.ts
  v3/src/components/error-tester/error-tester.tsx
  v3/src/hooks/use-uncaught-error-handler.tsx
  v3/src/models/data/attribute-types.ts
  v3/src/models/data/attribute.ts
  v3/src/register-tile-types.ts
  v3/src/utilities/environment-utils.ts
  v3/src/utilities/translation/lang/en-US.json5
  v3/src/utilities/url-params.ts
Labels: run regression

#2041 Codap-694 Position New Tiles Within Viewport
  v3/src/utilities/view-utils.ts
Labels: v3, run regression

#2049 Codap-774 Focus Flipped Tile
  v3/cypress/e2e/case-card.spec.ts
  v3/src/components/case-tile-common/case-tile-utils.ts
Labels: v3, run regression

#2047 Codap-81 Unsaved Changes Warning
  v3/cypress/e2e/adornments.spec.ts
  v3/cypress/e2e/attribute-types.spec.ts
  v3/cypress/e2e/axis.spec.ts
  v3/cypress/e2e/bivariate-adornments.spec.ts
  v3/cypress/e2e/calculator.spec.ts
  v3/cypress/e2e/case-card.spec.ts
  v3/cypress/e2e/cfm.spec.ts
  v3/cypress/e2e/component.spec.ts
  v3/cypress/e2e/formula/formula-component.spec.ts
  v3/cypress/e2e/formula/formula-errors.spec.ts
  v3/cypress/e2e/formula/formula-functions.spec.ts
  v3/cypress/e2e/formula/formula-hierarchical-tables.spec.ts
  v3/cypress/e2e/formula/formula-special-characters.spec.ts
  v3/cypress/e2e/graph-legend.spec.ts
  v3/cypress/e2e/graph.spec.ts
  v3/cypress/e2e/hierarchical-table.spec.ts
  v3/cypress/e2e/import-v2.spec.ts
  v3/cypress/e2e/map.spec.ts
  v3/cypress/e2e/pixi-interaction/graph-pixi-interaction.spec.ts
  v3/cypress/e2e/pixi-interaction/map-pixi-interaction.spec.ts
  v3/cypress/e2e/plugin.spec.ts
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/cypress/e2e/table.spec.ts
  v3/cypress/e2e/text.spec.ts
  v3/cypress/e2e/tool-shelf.spec.ts
  v3/src/components/app.tsx
  v3/src/utilities/translation/lang/en-US.json5
  v3/src/utilities/url-params.ts
Labels: v3, run regression

#2050 feat: v2 import/export for plugins
  v3/src/components/calculator/calculator-registration.ts
  v3/src/components/case-card/case-card-registration.ts
  v3/src/components/case-table/case-table-registration.ts
  v3/src/components/case-tile-common/inspector-panel/dataset-info-modal.tsx
  v3/src/components/component-title-bar.test.tsx
  v3/src/components/component-title-bar.tsx
  v3/src/components/graph/v2-graph-importer.ts
  v3/src/components/map/v2-map-importer.ts
  v3/src/components/slider/slider-registration.ts
  v3/src/components/text/text-registration.ts
  v3/src/components/web-view/web-view-model.ts
  v3/src/components/web-view/web-view-registration.test.ts
  v3/src/components/web-view/web-view-registration.ts
  v3/src/data-interactive/data-interactive-type-utils.test.ts
  v3/src/data-interactive/data-interactive-type-utils.ts
  v3/src/models/data/data-set.ts
  v3/src/models/data/v2-model.test.ts
  v3/src/models/data/v2-model.ts
  v3/src/models/data/v2-user-title-model.test.ts
  v3/src/models/data/v2-user-title-model.ts
  v3/src/models/tiles/tile-model.ts
  v3/src/test/v2/markov-example.codap
  v3/src/v2/codap-v2-data-context-types.ts
  v3/src/v2/codap-v2-data-set-importer.ts
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-tile-exporters.ts
  v3/src/v2/codap-v2-types.ts
  v3/src/v2/export-v2-document.ts
Labels: v3, run regression

#2040 CODAP-83 add recover deleted formula
  v3/cypress/e2e/table.spec.ts
  v3/cypress/support/elements/table-tile.ts
  v3/src/components/case-tile-common/attribute-menu/attribute-menu-list.tsx
  v3/src/data-interactive/data-interactive-type-utils.ts
  v3/src/models/shared/data-set-metadata.ts
  v3/src/v2/codap-v2-data-set-importer.ts
Labels: v3, run regression

#2053 Codap-803 Inspector Panel Restyle
  v3/src/assets/icons/icon-camera.svg
  v3/src/assets/icons/icon-hideShow.svg
  v3/src/assets/icons/icon-info.svg
  v3/src/assets/icons/icon-scaleData.svg
  v3/src/assets/icons/inspector-panel/configuration-icon.svg
  v3/src/assets/icons/inspector-panel/data-icon.svg
  v3/src/assets/icons/inspector-panel/delete-icon.svg
  v3/src/assets/icons/inspector-panel/format-icon.svg
  v3/src/assets/icons/inspector-panel/image-icon.svg
  v3/src/assets/icons/inspector-panel/info-icon.svg
  v3/src/assets/icons/inspector-panel/layers-icon.svg
  v3/src/assets/icons/inspector-panel/playback-settings-icon.svg
  v3/src/assets/icons/inspector-panel/resize-icon.svg
  v3/src/assets/icons/inspector-panel/timeline-scale-icon.svg
  v3/src/assets/icons/inspector-panel/view-icon.svg
  v3/src/assets/icons/inspector-panel/web-page-icon.svg
  v3/src/components/case-tile-common/inspector-panel/case-tile-inspector.tsx
  v3/src/components/component-title-bar.scss
  v3/src/components/graph/components/graph-inspector.tsx
  v3/src/components/inspector-panel.scss
  v3/src/components/inspector-panel.tsx
  v3/src/components/map/components/map-inspector.tsx
  v3/src/components/slider/slider-inspector.tsx
  v3/src/components/vars.scss
  v3/src/components/web-view/web-view-inspector.scss
  v3/src/components/web-view/web-view-inspector.tsx
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#2056 Codap-775 Fix Dropping on Overlapping Tiles
  v3/src/lib/dnd-kit/dnd-detect-collision.ts
Labels: v3, run regression

#2057 Convert Unimplemented Menu Items from Toast to Under Construction
  v3/src/components/beta/unimplemented-menu-item.tsx
  v3/src/components/graph/components/camera-menu-list.tsx
  v3/src/components/map/components/inspector-panel/save-image-menu-list.tsx
Labels: v3, run regression

#2059 CODAP-792 Make rescale button for bar chart work
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/plots/bar-chart/bar-chart-model.ts
  v3/src/components/graph/plots/plot-model.ts
Labels: v3, run regression

#2058 Codap-803 Inspector Panel Restyle Follow Up
  v3/src/assets/icons/inspector-panel/rescale-icon.svg
  v3/src/assets/icons/inspector-panel/web-page-icon.svg
  v3/src/assets/icons/inspector-panel/web-url-icon.svg
  v3/src/components/graph/components/graph-inspector.tsx
  v3/src/components/inspector-panel.scss
  v3/src/components/inspector-panel.tsx
  v3/src/components/map/components/map-inspector.tsx
  v3/src/components/web-view/web-view-inspector.tsx
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#2062 feat: more CODAP/CFM toolbar styling
  v3/cypress/e2e/map.spec.ts
  v3/cypress/e2e/plugin.spec.ts
  v3/cypress/e2e/tool-shelf.spec.ts
  v3/cypress/support/elements/cfm.ts
  v3/cypress/support/elements/toolbar-elements.ts
  v3/package-lock.json
  v3/package.json
  v3/src/assets/cfm/codap-project-icon.nosvgr.svg
  v3/src/assets/cfm/icon-help.nosvgr.svg
  v3/src/assets/cfm/icon-settings.nosvgr.svg
  v3/src/assets/cfm/icon-toolbar-position.nosvgr.svg
  v3/src/assets/cfm/web-policy-page-icon.nosvgr.svg
  v3/src/assets/icons/icon-codap-project.svg
  v3/src/assets/icons/icon-help-forum.svg
  v3/src/assets/icons/icon-help-pages.svg
  v3/src/assets/icons/web-page-icon.svg
  v3/src/components/tool-shelf/help-button.tsx
  v3/src/components/tool-shelf/settings-button.tsx
  v3/src/components/tool-shelf/tool-shelf.scss
  v3/src/components/tool-shelf/tool-shelf.tsx
  v3/src/components/web-view/web-view-inspector.tsx
  v3/src/components/web-view/web-view-model.ts
  v3/src/components/web-view/web-view-registration.ts
  v3/src/lib/cfm/use-cloud-file-manager.ts
  v3/src/models/tiles/tile-component-info.ts
  v3/src/models/ui-state.ts
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#2063 feat: beta release saves in v2 format by default [CODAP-813]
  v3/src/lib/config.ts
Labels: v3, run regression

#2064 Codap-814 Update Tile Minimize and Close Icons
  v3/src/assets/icons/close-tile-icon.svg
  v3/src/assets/icons/icon-minimize-active.svg
  v3/src/assets/icons/icon-minimize-hover.svg
  v3/src/assets/icons/icon-minimize.svg
  v3/src/assets/icons/minimize-tile-icon.svg
  v3/src/components/component-title-bar.scss
  v3/src/components/component-title-bar.tsx
Labels: v3, run regression

#2060 Codap-101 Import Dataset Metadata
  v3/cypress/e2e/table.spec.ts
  v3/src/components/case-tile-common/inspector-panel/dataset-info-modal.tsx
  v3/src/data-interactive/handlers/data-context-handler.test.ts
  v3/src/data-interactive/handlers/data-context-handler.ts
Labels: v3, run regression

#2067 chore: update CFM version to fix CFM menu issues
  v3/package-lock.json
  v3/package.json
Labels: v3, run regression
