Repository concord-consortium/codap, pull requests merged in 2025-01, with the labels that each got.

#1708 staging build 3.0.0-pre.2076
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1706 fix: assign unique names to new data sets
  v3/src/components/case-table/case-table-tool-shelf-button.tsx
  v3/src/utilities/js-utils.ts
Labels: v3, run regression

#1709 fix: don't write out empty case table name when exporting to v2 document
  v3/src/components/case-table/case-table-registration.ts
Labels: v3, run regression

#1710 fix: default numeric precision is two decimal places
  v3/cypress/e2e/formula/formula-functions.spec.ts
  v3/src/models/data/attribute-types.ts
Labels: v3, run regression

#1716 fix: wordListMatches() updates on dependent changes
  v3/eslint.config.mjs
  v3/src/models/formula/attribute-formula-adapter.ts
  v3/src/models/formula/formula-observers.test.ts
  v3/src/models/formula/formula-observers.ts
  v3/src/models/formula/formula-types.ts
  v3/src/models/formula/functions/lookup-functions.ts
  v3/src/models/formula/functions/string-functions.ts
Labels: v3, run regression

#1713 188565497 map filter formula
  v3/src/components/data-display/models/data-display-content-model.ts
  v3/src/components/data-display/models/data-display-filter-formula-adapter.ts
  v3/src/components/graph/adornments/base-graph-formula-adapter.ts
  v3/src/components/graph/adornments/plotted-function/plotted-function-formula-adapter.test.ts
  v3/src/components/graph/adornments/univariate-measures/plotted-value/plotted-value-formula-adapter.test.ts
  v3/src/components/graph/graph-registration.ts
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/models/graph-filter-formula-adapter.ts
  v3/src/components/map/map-registration.ts
  v3/src/components/map/models/map-content-model.ts
  v3/src/components/map/models/map-filter-formula-adapter.ts
  v3/src/models/formula/formula-manager-types.ts
  v3/src/models/formula/formula-manager.test.ts
  v3/src/models/tiles/tile-content-info.ts
Labels: v3, run regression

#1697 188651494 pixi js integration
  .github/workflows/ci.yml
  .github/workflows/graph-pixi-tests.yml
  .github/workflows/v3.yml
  v3/README.md
  v3/cypress/e2e/graph.spec.ts
  v3/cypress/e2e/pixi-interaction/graph-pixi-interaction.spec.ts
  v3/cypress/e2e/pixi-interaction/map-pixi-interaction.spec.ts
  v3/cypress/support/helpers/graph-canvas-helper.ts
  v3/cypress/support/helpers/map-canvas-helper.ts
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/map/components/codap-map.tsx
  v3/src/lib/debug.ts
Labels: v3, run regression

#1715 Adds ability to rename attribute in formula editor modal.
  v3/src/components/common/edit-attribute-formula-modal.tsx
  v3/src/components/common/edit-formula-modal.scss
  v3/src/components/common/edit-formula-modal.tsx
Labels: v3, run regression

#1718 Adds CSS styling for text tile headings
  v3/src/components/text/text-tile.scss
Labels: v3

#1714 Implement draggable input row [PT-187958658]
  v3/src/components/case-table/case-table-component.test.tsx
  v3/src/components/case-table/case-table-drag-drop.ts
  v3/src/components/case-table/case-table-shared.scss.d.ts
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-table/row-divider.tsx
  v3/src/components/case-table/row-drag-overlay.scss
  v3/src/components/case-table/row-drag-overlay.tsx
  v3/src/components/case-table/use-index-column.tsx
  v3/src/hooks/use-drag-drop.ts
Labels: v3, run regression

#1692 feat: export graph image snapshot (PT-188650872)
  v3/cypress.config.ts
  v3/cypress/e2e/graph.spec.ts
  v3/src/components/app.tsx
  v3/src/components/data-display/components/legend/categorical-legend.tsx
  v3/src/components/data-display/components/legend/color-legend.tsx
  v3/src/components/data-display/components/legend/numeric-legend.tsx
  v3/src/components/data-display/models/data-display-content-model.ts
  v3/src/components/data-display/models/data-display-render-state.ts
  v3/src/components/graph/components/camera-menu-list.tsx
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/graph-data-display-handler.test.ts
  v3/src/components/graph/graph-data-display-handler.ts
  v3/src/components/graph/graph-registration.ts
  v3/src/components/graph/utilities/image-utils.test.ts
  v3/src/components/graph/utilities/image-utils.ts
  v3/src/data-interactive/data-interactive-types.ts
  v3/src/data-interactive/handlers/data-display-handler.ts
  v3/src/data-interactive/handlers/di-results.ts
  v3/src/data-interactive/register-handlers.ts
  v3/src/data-interactive/resource-parser.ts
  v3/src/hooks/use-cfm-context.ts
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#1719 breakup some dependency trees
  .github/workflows/v3.yml
  v3/src/components/axis/axis-constants.ts
  v3/src/components/axis/axis-utils.ts
  v3/src/components/axis/components/sub-axis.tsx
  v3/src/components/axis/helper-models/axis-helper.test.ts
  v3/src/components/axis/helper-models/axis-helper.ts
  v3/src/components/axis/helper-models/categorical-axis-helper.ts
  v3/src/components/axis/helper-models/date-axis-helper.test.ts
  v3/src/components/axis/helper-models/date-axis-helper.ts
  v3/src/components/axis/helper-models/numeric-axis-helper.test.ts
  v3/src/components/axis/helper-models/numeric-axis-helper.ts
  v3/src/components/axis/hooks/use-axis-provider-context.ts
  v3/src/components/axis/hooks/use-axis.test.tsx
  v3/src/components/axis/hooks/use-axis.ts
  v3/src/components/axis/hooks/use-sub-axis.ts
  v3/src/components/data-display/components/attribute-label.tsx
  v3/src/components/data-display/components/legend/multi-legend.tsx
  v3/src/components/data-display/hooks/use-base-data-display-model.ts
  v3/src/components/data-display/hooks/use-data-display-animation.ts
  v3/src/components/data-display/hooks/use-data-display-model.ts
  v3/src/components/data-display/models/base-data-display-content-model.ts
  v3/src/components/data-display/models/data-display-content-model.ts
  v3/src/components/graph/graphing-types.ts
  v3/src/components/graph/hooks/use-graph-content-model-context.ts
  v3/src/components/map/hooks/use-map-model-context.ts
  v3/src/components/slider/slider-model.ts
Labels: v3, run regression

#1721 feat: export text tile in v2 format
  v3/src/components/text/text-defs.ts
  v3/src/components/text/text-model.ts
  v3/src/components/text/text-registration.test.ts
  v3/src/components/text/text-registration.ts
  v3/src/data-interactive/data-interactive-component-types.ts
Labels: v3, run regression

#1722 extract kIndexColumnKey
  v3/src/components/case-tile-common/attribute-header-divider.tsx
  v3/src/components/common/edit-formula-modal.tsx
  v3/src/models/data/data-set-utils.ts
Labels: v3, run regression

#1720 Focuses cursor in new table title bar on create.
  v3/cypress/e2e/plugin.spec.ts
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/cypress/e2e/table.spec.ts
  v3/cypress/e2e/tool-shelf.spec.ts
  v3/cypress/support/elements/component-elements.ts
  v3/package.json
  v3/src/components/case-table/case-table-tool-shelf-button.tsx
  v3/src/components/case-tile-common/case-tile-title-bar.tsx
  v3/src/components/component-title-bar.tsx
  v3/src/components/tiles/tile-base-props.ts
  v3/src/models/codap/create-tile.ts
  v3/src/models/tiles/tile-model.ts
Labels: v3, run regression

#1717 188276475 case table filter formula UI
  v3/cypress/e2e/case-card.spec.ts
  v3/cypress/support/elements/card-tile.ts
  v3/src/components/case-card/case-card.tsx
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-table/case-table.tsx
  v3/src/components/case-tile-common/filter-formula-bar.scss
  v3/src/components/case-tile-common/filter-formula-bar.tsx
  v3/src/components/case-tile-common/hide-show-menu-list.tsx
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#1727 V3 release 3.0.0 pre.2090
  v3/CHANGELOG.md
  v3/cypress/e2e/table.spec.ts
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1707 Categorical axis limits number of categories to space available
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/src/components/axis/components/sub-axis.tsx
  v3/src/components/axis/helper-models/categorical-axis-helper.ts
  v3/src/components/axis/hooks/use-sub-axis.ts
  v3/src/components/axis/models/multi-scale.ts
  v3/src/components/data-display/components/legend/categorical-legend.tsx
  v3/src/components/data-display/data-display-types.ts
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/adornments/adornment-utils.ts
  v3/src/components/graph/adornments/adornments.tsx
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-component.tsx
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.ts
  v3/src/components/graph/adornments/movable-value/movable-value-adornment-component.tsx
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-model.ts
  v3/src/components/graph/components/dot-chart-bars.tsx
  v3/src/components/graph/components/freedotplotdots.tsx
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/models/graph-data-configuration-model.test.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/components/graph/utilities/dot-plot-utils.ts
Labels: v3, run regression

#1725 fix: v2 text export
  v3/src/components/text/text-registration.test.ts
  v3/src/components/text/text-registration.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1731 fix: default name of text tile
  v3/src/components/text/text-registration.ts
Labels: v3, run regression

#1729 Fixes broken case table filter cypress test
  v3/cypress/e2e/table.spec.ts
  v3/cypress/support/elements/table-tile.ts
Labels: v3, run regression

#1723 simplify plugin drop support
  v3/src/components/web-view/web-view-drop-overlay.tsx
Labels: v3, run regression

#1733 make TileContentModel more independent
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/models/document/document-content.ts
  v3/src/models/shared/shared-model-manager.ts
  v3/src/models/shared/shared-model.ts
  v3/src/models/tiles/tile-content.ts
Labels: run regression

#1734 break dependencies around the formula system
  v3/src/components/app.tsx
  v3/src/components/data-display/models/data-display-filter-formula-adapter.ts
  v3/src/components/graph/adornments/base-graph-formula-adapter.ts
  v3/src/components/graph/adornments/plotted-function/plotted-function-formula-adapter.ts
  v3/src/components/graph/adornments/univariate-measures/plotted-value/plotted-value-formula-adapter.ts
  v3/src/components/graph/models/graph-filter-formula-adapter.ts
  v3/src/components/map/models/map-filter-formula-adapter.ts
  v3/src/models/codap/create-codap-document.ts
  v3/src/models/data/attribute.test.ts
  v3/src/models/data/data-set-conversion.ts
  v3/src/models/data/data-set-utils.ts
  v3/src/models/formula/attribute-formula-adapter.test.ts
  v3/src/models/formula/attribute-formula-adapter.ts
  v3/src/models/formula/filter-formula-adapter.test.ts
  v3/src/models/formula/filter-formula-adapter.ts
  v3/src/models/formula/formula-adapter-registry.ts
  v3/src/models/formula/formula-manager-adapter.ts
  v3/src/models/formula/formula-manager-types.ts
  v3/src/models/formula/formula-manager.test.ts
  v3/src/models/formula/formula-manager.ts
  v3/src/models/formula/formula-observers.ts
  v3/src/models/formula/formula-types.ts
  v3/src/models/formula/formula.test.ts
  v3/src/models/formula/formula.ts
  v3/src/models/tiles/tile-content-info.ts
  v3/src/models/tiles/tile-environment.ts
Labels: v3, run regression

#1735 HistoryService take 2
  v3/src/components/axis/models/axis-model.test.ts
  v3/src/components/case-card/case-card.tsx
  v3/src/components/case-card/case-card.v2.test.tsx
  v3/src/components/case-table/case-table.tsx
  v3/src/components/case-table/cell-text-editor.test.tsx
  v3/src/components/slider/slider-model.test.ts
  v3/src/components/web-view/web-view-drop-overlay.tsx
  v3/src/data-interactive/handlers/attribute-handler.test.ts
  v3/src/data-interactive/handlers/handler-test-utils.ts
  v3/src/data-interactive/handlers/selection-list-handler.test.ts
  v3/src/data-interactive/notification-core-types.ts
  v3/src/data-interactive/notification-full-types.ts
  v3/src/lib/dnd-kit/dnd-notifications.ts
  v3/src/lib/log-message.ts
  v3/src/models/data/data-set-utils.test.ts
  v3/src/models/data/data-set-utils.ts
  v3/src/models/document/create-document-model.ts
  v3/src/models/history/app-history-service.ts
  v3/src/models/history/apply-model-change.ts
  v3/src/models/history/history-service.ts
  v3/src/models/tiles/tile-environment.ts
Labels: v3, run regression

#1737 add without-undo to the history service take 2
  v3/src/models/history/app-history-service.ts
  v3/src/models/history/apply-model-change.ts
  v3/src/models/history/history-service.ts
  v3/src/models/history/without-undo.ts
  v3/src/utilities/mst.test.ts
Labels: v3, run regression

#1739 split getGlobalValueManager
  v3/src/components/common/formula-editor.tsx
  v3/src/components/common/formula-insert-values-menu.tsx
  v3/src/components/slider/component-handler-slider.test.ts
  v3/src/components/slider/slider-model.ts
  v3/src/components/slider/slider-registration.test.ts
  v3/src/components/slider/slider-registration.ts
  v3/src/data-interactive/handlers/global-handler.ts
  v3/src/data-interactive/handlers/global-list-handler.ts
  v3/src/data-interactive/resource-parser-utils.ts
  v3/src/data-interactive/resource-parser.test.ts
  v3/src/models/formula/test-utils/formula-test-utils.ts
  v3/src/models/global/global-value-manager.ts
  v3/src/models/tiles/tile-environment.ts
  v3/src/v2/export-v2-document.test.ts
  v3/src/v2/export-v2-document.ts
Labels: v3, run regression

#1740 split data set linking from shared-data-utils
  v3/src/models/document/data-set-linking.test.ts
  v3/src/models/document/data-set-linking.ts
  v3/src/models/document/document-content.ts
  v3/src/models/shared/shared-data-utils.test.ts
  v3/src/models/shared/shared-data-utils.ts
Labels: v3, run regression

#1726 181904766 graph title attr collection
  v3/cypress/e2e/graph.spec.ts
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/src/components/graph/graph-registration.ts
  v3/src/models/data/v2-model.test.ts
  v3/src/models/data/v2-model.ts
Labels: v3, run regression

#1741 split out v2 dataset conversion
  v3/src/components/app.tsx
  v3/src/models/data/data-set-notification-adapter-v2.ts
  v3/src/models/data/data-set-notification-adapter.ts
  v3/src/models/data/data-set-notifications.ts
Labels: run regression

#1746 handle vertical movable lines
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-model.test.ts
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-model.ts
  v3/src/utilities/json-number.test.ts
  v3/src/utilities/json-number.ts
Labels: v3, run regression

#1747 fix: case selection is saved/restored
  v3/src/models/data/data-set.test.ts
  v3/src/models/data/data-set.ts
Labels: v3, run regression

#1744 separate tile selection context
  v3/src/components/case-table/case-table-component.test.tsx
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-table/use-white-space-click.ts
  v3/src/components/case-tile-common/collection-title.tsx
  v3/src/components/codap-component.tsx
  v3/src/components/data-display/hooks/use-pixi-pointer-down.ts
  v3/src/components/graph/adornments/adornments.tsx
  v3/src/components/graph/components/graph-attribute-label.tsx
  v3/src/components/text/text-tile.tsx
  v3/src/components/text/text-toolbar.tsx
  v3/src/hooks/use-drag-drop.ts
  v3/src/hooks/use-tile-model-context.ts
  v3/src/hooks/use-tile-selection-context.ts
Labels: v3, run regression

#1742 Adds styling to links in text component
  v3/src/components/text/text-tile.scss
Labels: v3

#1743 Removes the codap-modal min-height and min-width css
  v3/src/components/common/edit-formula-modal.scss
Labels: v3

#1752 Trimming imported and manually entered values
  v3/src/models/data/attribute-types.ts
Labels: v3

#1750 Allow 2 y-attrs when x-attribute is date
  v3/src/components/graph/models/graph-data-configuration-model.ts
Labels: v3

#1749 Fix crash on resize categorical
  v3/src/components/data-display/models/data-configuration-model.ts
Labels: v3

#1754 remove extra semicolons
  v3/src/utilities/json-number.test.ts
  v3/src/utilities/json-number.ts
Labels: v3, run regression

#1753 split out the data set types from data-interactive-types
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/data-interactive/data-interactive-data-set-types.ts
  v3/src/data-interactive/data-interactive-type-utils.ts
  v3/src/data-interactive/data-interactive-types.ts
  v3/src/data-interactive/data-interactive-utils.ts
  v3/src/data-interactive/handlers/all-cases-handler.test.ts
  v3/src/data-interactive/handlers/attribute-handler.ts
  v3/src/data-interactive/handlers/attribute-location-handler.ts
  v3/src/data-interactive/handlers/case-by-id-handler.test.ts
  v3/src/data-interactive/handlers/case-by-index-handler.test.ts
  v3/src/data-interactive/handlers/case-formula-search-handler.test.ts
  v3/src/data-interactive/handlers/case-handler.test.ts
  v3/src/data-interactive/handlers/case-handler.ts
  v3/src/data-interactive/handlers/case-search-handler.test.ts
  v3/src/data-interactive/handlers/collection-handler.test.ts
  v3/src/data-interactive/handlers/collection-handler.ts
  v3/src/data-interactive/handlers/collection-list-handler.test.ts
  v3/src/data-interactive/handlers/data-context-handler.test.ts
  v3/src/data-interactive/handlers/data-context-handler.ts
  v3/src/data-interactive/handlers/data-context-list-handler.test.ts
  v3/src/data-interactive/handlers/di-handler-utils.ts
  v3/src/data-interactive/handlers/handler-functions.ts
  v3/src/data-interactive/handlers/item-by-case-id-handler.test.ts
  v3/src/data-interactive/handlers/item-by-id-handler.test.ts
  v3/src/data-interactive/handlers/item-handler.test.ts
  v3/src/data-interactive/handlers/item-handler.ts
  v3/src/data-interactive/handlers/item-search-handler.test.ts
  v3/src/data-interactive/handlers/selection-list-handler.test.ts
Labels: v3, run regression

#1755 split out the v3 data set types
  v3/src/components/graph/v2-graph-importer.ts
  v3/src/components/map/v2-map-importer.ts
  v3/src/data-interactive/data-interactive-data-set-types.ts
  v3/src/data-interactive/data-interactive-type-utils.ts
  v3/src/data-interactive/data-interactive-types.ts
  v3/src/data-interactive/handlers/attribute-handler.test.ts
  v3/src/data-interactive/handlers/attribute-list-handler.test.ts
  v3/src/data-interactive/handlers/collection-handler.test.ts
  v3/src/data-interactive/handlers/collection-handler.ts
  v3/src/data-interactive/handlers/data-context-handler.test.ts
  v3/src/v2/codap-v2-data-set-types.ts
  v3/src/v2/codap-v2-document.ts
  v3/src/v2/codap-v2-types.ts
  v3/src/v2/export-v2-document.test.ts
  v3/src/v2/export-v2-document.ts
Labels: v3, run regression

#1748 Fix graph's displayOnlySelected and axis rerendering touchups
  v3/cypress/e2e/axis.spec.ts
  v3/src/components/axis/helper-models/date-axis-helper.ts
  v3/src/components/axis/hooks/use-sub-axis.ts
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/data-display/pixi/pixi-points.ts
  v3/src/components/graph/components/inspector-panel/hide-show-menu-list.tsx
  v3/src/components/graph/hooks/use-plot.ts
  v3/src/components/graph/models/graph-content-model.ts
Labels: v3, run regression

#1757 Fix to accidentally broken axis cypress test
  v3/cypress/e2e/axis.spec.ts
Labels: v3

#1758 fix: fix attribute date-typing
  v3/src/models/data/attribute.ts
Labels: v3, run regression

#1756 Fix for legend response to selection bug
  v3/src/components/data-display/components/legend/categorical-legend.tsx
  v3/src/components/data-display/components/legend/numeric-legend.tsx
Labels: v3, run regression

#1736 188616850 map export v2
  v3/src/components/map/components/codap-map.tsx
  v3/src/components/map/map-registration.ts
  v3/src/components/map/models/map-content-model.ts
  v3/src/components/map/v2-map-exporter.ts
  v3/src/components/map/v2-map-importer.test.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1745 feat: initial v2 graph export
  v3/src/components/graph/graph-registration.ts
  v3/src/components/graph/v2-graph-exporter.test.ts
  v3/src/components/graph/v2-graph-exporter.ts
  v3/src/components/graph/v2-graph-importer.test.ts
  v3/src/test/v2/mammals-all-diet-legends.codap
  v3/src/test/v2/mammals-all-graphs.codap
  v3/src/test/v2/mammals-all-speed-legends.codap
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1759 Trim attribute names on csv import
  v3/src/models/data/attribute.ts
  v3/src/utilities/csv-import.ts
Labels: v3

#1760 extract v2 data set importer
  v3/src/models/data/data-set.ts
  v3/src/v2/codap-v2-data-set-importer.ts
  v3/src/v2/codap-v2-document.ts
Labels: v3, run regression

#1762 reduce reasons for re-rendering top level components
  v3/src/components/case-card/case-card.tsx
  v3/src/components/case-table/case-table-component.tsx
  v3/src/components/case-table/case-table.tsx
  v3/src/components/container/container.tsx
  v3/src/components/drag-drop/attribute-drag-overlay.tsx
  v3/src/components/graph/components/graph-component.tsx
  v3/src/components/map/components/map-component.tsx
  v3/src/hooks/use-drag-drop.ts
Labels: v3, run regression

#1763 staging build 3.0.0-pre.2128
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1765 Fix drag-rearrange of categories bug
  v3/src/components/axis/helper-models/categorical-axis-helper.ts
  v3/src/components/axis/hooks/use-sub-axis.ts
  v3/src/components/graph/hooks/use-plot.ts
Labels: v3

#1766 188651787 card attribute rename
  v3/src/components/case-tile-common/attribute-header.tsx
Labels: v3, run regression

#1764 Fixes date precision in case card
  v3/src/components/case-tile-common/attribute-format-utils.tsx
Labels: v3, run regression

#1767 Adornments respond to changes in selection if only showing measures for selection
  v3/src/components/graph/adornments/adornments.tsx
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-model.ts
  v3/src/components/graph/components/inspector-panel/hide-show-menu-list.tsx
  v3/src/components/graph/graph-component-handler.test.ts
  v3/src/components/graph/graph-component-handler.ts
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/components/graph/models/graph-model.test.ts
Labels: v3, run regression

#1761 188575507 color functions
  v3/src/assets/json/function-strings.json5
  v3/src/models/formula/functions/color-functions.test.ts
  v3/src/models/formula/functions/color-functions.ts
  v3/src/models/formula/functions/math.ts
Labels: v3, run regression

#1768 Adds a zero axis line when graph is a dotPlot with points as bars
  v3/src/components/axis/components/axis.tsx
  v3/src/components/axis/components/sub-axis.tsx
  v3/src/components/axis/helper-models/numeric-axis-helper.ts
  v3/src/components/axis/hooks/use-sub-axis.ts
  v3/src/components/graph/components/graph-axis.tsx
  v3/src/components/graph/models/graph-content-model.ts
Labels: v3, run regression

#1769 make cachedFnWithArgsFactory observable
  v3/src/utilities/mst-utils.ts
Labels: run regression

#1777 Fix transition from numeric to categorical axis
  v3/src/components/axis/helper-models/numeric-axis-helper.ts
  v3/src/components/axis/hooks/use-sub-axis.ts
Labels: v3

#1770 Propagate null value in arithmetic
  v3/src/models/formula/functions/operators.test.ts
  v3/src/models/formula/functions/operators.ts
Labels: v3, run regression

#1772 categorical legend refactor
  v3/src/components/data-display/components/legend/categorical-legend-model.ts
  v3/src/components/data-display/components/legend/categorical-legend.tsx
  v3/src/components/data-display/models/data-configuration-model.ts
Labels: run regression

#1773 Remove the defocus when we are already in input mode
  v3/src/components/case-tile-common/attribute-header.tsx
Labels: v3, run regression

#1771 feat: export simple adornments in v2 format
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/adornments/adornment-content-info.ts
  v3/src/components/graph/adornments/adornment-models.ts
  v3/src/components/graph/adornments/adornment-types.ts
  v3/src/components/graph/adornments/adornments-base-store.ts
  v3/src/components/graph/adornments/adornments.tsx
  v3/src/components/graph/adornments/count/count-adornment-model.ts
  v3/src/components/graph/adornments/count/count-adornment-registration.tsx
  v3/src/components/graph/adornments/movable-value/movable-value-adornment-model.ts
  v3/src/components/graph/adornments/movable-value/movable-value-adornment-registration.tsx
  v3/src/components/graph/adornments/plotted-function/plotted-function-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/mean-absolute-deviation/mean-absolute-deviation-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/mean-absolute-deviation/mean-absolute-deviation-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/mean/mean-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/median/median-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/plotted-value/plotted-value-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/standard-deviation/standard-deviation-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/standard-deviation/standard-deviation-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/standard-error/standard-error-adornment-registration.tsx
  v3/src/components/graph/adornments/v2-adornment-importer-types.ts
  v3/src/components/graph/adornments/v2-adornment-importer.test.ts
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/graph-component-handler.test.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/components/graph/v2-graph-exporter.test.ts
  v3/src/components/graph/v2-graph-exporter.ts
  v3/src/test/v2/mammals-simple-adornments.codap
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1774 feat: v2 export of LSRL adornment
  v3/src/components/graph/adornments/adornment-content-info.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-registration.tsx
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/v2-graph-exporter.test.ts
  v3/src/components/graph/v2-graph-exporter.ts
  v3/src/test/v2/mammals-lsrl-adornment.codap
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1776 feat: v2 export of movable lines and points
  v3/src/components/graph/adornments/adornment-models.ts
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-model.ts
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-registration.tsx
  v3/src/components/graph/adornments/movable-point/movable-point-adornment-model.ts
  v3/src/components/graph/adornments/movable-point/movable-point-adornment-registration.tsx
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/v2-graph-exporter.test.ts
  v3/src/components/graph/v2-graph-exporter.ts
  v3/src/test/v2/mammals-movable-line-point-adornments.codap
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression
