Repository concord-consortium/codap, pull requests merged in 2025-02, with the labels that each got.

#1780 staging version 3.0.0-pre.2144
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1778 188839221 Fix Legend Select
  v3/src/components/data-display/models/data-configuration-model.ts
Labels: v3, run regression

#1779 feat: import/export univariate measure adornment labels
  v3/src/components/graph/adornments/adornment-content-info.ts
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-component.tsx
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-model.test.ts
  v3/src/components/graph/adornments/univariate-measures/box-plot/box-plot-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/mean-absolute-deviation/mean-absolute-deviation-adornment-model.test.ts
  v3/src/components/graph/adornments/univariate-measures/mean-absolute-deviation/mean-absolute-deviation-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/mean/mean-adornment-model.test.ts
  v3/src/components/graph/adornments/univariate-measures/mean/mean-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/median/median-adornment-model.test.ts
  v3/src/components/graph/adornments/univariate-measures/median/median-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-component.tsx
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-model.test.ts
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/standard-deviation/standard-deviation-adornment-model.test.ts
  v3/src/components/graph/adornments/univariate-measures/standard-deviation/standard-deviation-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/standard-error/standard-error-adornment-component.tsx
  v3/src/components/graph/adornments/univariate-measures/standard-error/standard-error-adornment-model.test.ts
  v3/src/components/graph/adornments/univariate-measures/standard-error/standard-error-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-helper.ts
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-simple-component.tsx
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-utils.ts
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/hooks/use-adornment-attributes.ts
  v3/src/components/graph/v2-graph-exporter.test.ts
  v3/src/components/graph/v2-graph-exporter.ts
  v3/src/test/v2/mammals-adornment-labels.codap
Labels: v3, run regression

#1782 legend type based on the data configuration
  v3/src/components/data-display/components/legend/legend.tsx
Labels: v3, run regression

#1781 Remainder of adornments and show measures for selection
  v3/src/components/graph/adornments/count/count-adornment-component.tsx
  v3/src/components/graph/adornments/count/count-adornment-model.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-component.tsx
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.ts
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-model.ts
  v3/src/components/graph/components/scatter-plot-utils.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
Labels: v3

#1783 Changes to support a size legend
  v3/src/components/data-display/components/legend/legend.tsx
  v3/src/components/data-display/models/base-data-display-content-model.ts
Labels: run regression

#1785 Touchup to Show Measures for Selection
  v3/src/components/graph/adornments/count/count-adornment-component.tsx
  v3/src/components/graph/adornments/count/count-adornment-model.ts
Labels: v3

#1789 chore: downgrade chakra-ui
  v3/eslint.config.mjs
  v3/package-lock.json
  v3/package.json
Labels: v3, run regression

#1787 Update dependencies
  v3/doc/dependencies-notes.md
  v3/package-lock.json
  v3/package.json
  v3/src/components/data-display/pixi/pixi-points.ts
Labels: v3, run regression

#1790 feat: table does not become selected on attribute drag
  v3/src/components/case-table/case-table-component.test.tsx
  v3/src/components/case-table/case-table-drag-drop.ts
  v3/src/components/case-table/case-table.tsx
  v3/src/components/codap-component.tsx
  v3/src/components/container/free-tile-component.tsx
  v3/src/components/drag-drop/attribute-drag-overlay.scss
  v3/src/hooks/use-tile-selection-context.ts
  v3/src/lib/dnd-kit/dnd-detect-collision.ts
Labels: v3, run regression

#1786 feat: import/export regression line labels from/to v2
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-component.tsx
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.test.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-registration.tsx
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/utilities/graph-utils.test.ts
  v3/src/components/graph/utilities/graph-utils.ts
  v3/src/test/v2/mammals-adornment-labels.codap
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1775 Change attribute type to categorical with a date on opposite axis plot bug fix
  v3/src/components/graph/models/graph-model-utils.ts
Labels: v3, run regression

#1791 [#188862999] - Back ticks to attributes names with non-characters added via Insert Value button
  v3/src/components/common/formula-insert-values-menu.tsx
Labels: v3, run regression

#1793 feat: v2 import/export of movable line labels
  v3/src/components/graph/adornments/adornment-models.test.ts
  v3/src/components/graph/adornments/adornment-models.ts
  v3/src/components/graph/adornments/components/adornment-checkbox.tsx
  v3/src/components/graph/adornments/components/adornment.scss
  v3/src/components/graph/adornments/components/adornment.tsx
  v3/src/components/graph/adornments/components/adornments.scss
  v3/src/components/graph/adornments/components/adornments.tsx
  v3/src/components/graph/adornments/components/measures-for-selection-banner.scss
  v3/src/components/graph/adornments/components/measures-for-selection-banner.tsx
  v3/src/components/graph/adornments/count/count-adornment-component.tsx
  v3/src/components/graph/adornments/line-label-instance.ts
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-component.tsx
  v3/src/components/graph/adornments/lsrl/lsrl-adornment-model.ts
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-component.tsx
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-model.ts
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-registration.tsx
  v3/src/components/graph/adornments/movable-point/movable-point-adornment-model.ts
  v3/src/components/graph/adornments/movable-point/movable-point-adornment-registration.tsx
  v3/src/components/graph/adornments/movable-value/movable-value-adornment-component.tsx
  v3/src/components/graph/adornments/plotted-function/plotted-function-adornment-registration.tsx
  v3/src/components/graph/adornments/plotted-function/plotted-function-formula-adapter.ts
  v3/src/components/graph/adornments/point-model.ts
  v3/src/components/graph/adornments/store/adornments-base-store.ts
  v3/src/components/graph/adornments/store/adornments-store-utils.ts
  v3/src/components/graph/adornments/store/adornments-store.test.ts
  v3/src/components/graph/adornments/store/adornments-store.ts
  v3/src/components/graph/adornments/univariate-measures/mean-absolute-deviation/mean-absolute-deviation-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/mean/mean-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/median/median-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/normal-curve/normal-curve-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/plotted-value/plotted-value-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/plotted-value/plotted-value-formula-adapter.ts
  v3/src/components/graph/adornments/univariate-measures/standard-deviation/standard-deviation-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/standard-error/standard-error-adornment-registration.tsx
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-base-component.tsx
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-helper.ts
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-model.ts
  v3/src/components/graph/adornments/utilities/adornment-utils.test.ts
  v3/src/components/graph/adornments/utilities/adornment-utils.ts
  v3/src/components/graph/adornments/utilities/base-graph-formula-adapter.ts
  v3/src/components/graph/adornments/v2-adornment-importer-types.ts
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/components/graph.tsx
  v3/src/components/graph/components/inspector-panel/graph-measure-group.tsx
  v3/src/components/graph/components/inspector-panel/graph-measure-palette.tsx
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/components/graph/utilities/graph-utils.test.ts
  v3/src/components/graph/utilities/graph-utils.ts
  v3/src/test/v2/mammals-adornment-labels.codap
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1794 fix: create a copy of document with boundaries
  v3/src/models/boundaries/boundary-manager.ts
  v3/src/models/formula/attribute-formula-adapter.test.ts
  v3/src/models/formula/attribute-formula-adapter.ts
Labels: v3, run regression

#1792 188463252 checkbox case value
  v3/cypress/e2e/table.spec.ts
  v3/src/components/case-card/case-attr-view.scss
  v3/src/components/case-card/case-attr-view.tsx
  v3/src/components/case-table/attribute-value-cell.tsx
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-table/use-columns.tsx
  v3/src/components/case-table/use-rows.ts
  v3/src/components/case-tile-common/attribute-format-utils.tsx
  v3/src/components/case-tile-common/checkbox-cell.tsx
Labels: v3, run regression

#1796 add check for point compression interaction with categorical plots
  v3/cypress/e2e/pixi-interaction/graph-pixi-interaction.spec.ts
Labels: v3, run regression

#1795 use autorun in numeric legend
  v3/cypress/e2e/graph-legend.spec.ts
  v3/src/components/data-display/components/legend/numeric-legend.tsx
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/models/data/data-set.ts
  v3/src/utilities/mst-utils.test.ts
  v3/src/utilities/mst-utils.ts
Labels: v3, run regression

#1798 fix: case table cell click editing behavior
  v3/cypress/e2e/graph-legend.spec.ts
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/cypress/e2e/table.spec.ts
  v3/cypress/support/elements/table-tile.ts
  v3/patches/react-data-grid+7.0.0-beta.44.patch
  v3/src/components/case-table/use-selected-rows.ts
Labels: v3, run regression

#1804 feat: implement `notify` method of `formulaEngine` handler (evalExpression)
  v3/src/data-interactive/handlers/formula-engine-handler.test.ts
  v3/src/data-interactive/handlers/formula-engine-handler.ts
  v3/src/models/formula/functions/other-functions.ts
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#1801 Adds "index" to index column header
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-tile-common/attribute-header.tsx
Labels: v3, run regression

#1802 188616847 stroke point plot background color import/export V2
  v3/src/components/container/free-tile-row.scss
  v3/src/components/data-display/models/data-display-content-model.ts
  v3/src/components/graph/models/graph-content-model.ts
  v3/src/components/graph/v2-graph-exporter.test.ts
  v3/src/components/graph/v2-graph-exporter.ts
  v3/src/components/graph/v2-graph-importer.ts
  v3/src/test/v2/mammals-graph-formats.codap
  v3/src/utilities/color-utils.ts
Labels: v3, run regression

#1805 fix: movable line undo/redo issues
  v3/src/components/graph/adornments/adornment-models.ts
  v3/src/components/graph/adornments/movable-line/movable-line-adornment-component.tsx
  v3/src/components/graph/adornments/store/adornments-store.test.ts
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#1803 chore: improve v2 types for plot models
  v3/src/components/graph/adornments/adornment-content-info.ts
  v3/src/components/graph/adornments/v2-adornment-importer.ts
  v3/src/components/graph/v2-graph-exporter.ts
  v3/src/v2/codap-v2-types.ts
Labels: v3, run regression

#1808 Prevents selection of row when user clicks on checkbox
  v3/src/components/case-tile-common/checkbox-cell.tsx
Labels: run regression

#1807 [#188809846] Points plot in {0,0} when Other is a category
  v3/src/components/graph/models/graph-content-model.ts
Labels: v3, run regression

#1809 188883647 checkbox undo redo
  v3/src/components/case-tile-common/checkbox-cell.tsx
Labels: v3, run regression

#1810 fix flakey clicks
  v3/src/components/axis/components/axis-or-legend-attribute-menu.tsx
  v3/src/components/case-tile-common/attribute-header.tsx
  v3/src/components/case-tile-common/color-text-editor.tsx
  v3/src/components/container/free-tile-component.tsx
  v3/src/components/data-display/inspector/point-color-setting.tsx
  v3/src/components/inspector-panel.tsx
  v3/src/components/web-view/web-view-inspector.tsx
  v3/src/hooks/use-callback-ref.ts
  v3/src/hooks/use-outside-pointer-down.ts
Labels: v3, run regression

#1806 feat: implement first() and last() semi-aggregate functions
  v3/src/models/formula/functions/semi-aggregate-functions.test.ts
  v3/src/models/formula/functions/semi-aggregate-functions.ts
  v3/src/models/formula/test-utils/formula-test-utils.ts
Labels: v3, run regression

#1813 staging build 3.0.0-pre.2174
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1814 188868683 graph checkbox
  v3/src/components/case-tile-common/checkbox-cell.tsx
  v3/src/components/data-display/components/legend/legend.tsx
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/models/graph-model-utils.ts
Labels: v3, run regression

#1816 Changes the logic for applying movingStyle when tile is minimized
  v3/src/components/container/free-tile-component.tsx
Labels: v3, run regression

#1815 Fix date axis scaling bug
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/models/graph-data-configuration-model.ts
  v3/src/components/graph/models/graph-model-utils.ts
Labels: v3

#1818 fix: case table cell selection/editing (take two)
  v3/cypress/e2e/smoke/single-codap-smoke.ts
  v3/package.json
  v3/patches/react-data-grid+7.0.0-beta.44.patch
  v3/src/components/case-table/use-selected-rows.ts
Labels: v3, run regression

#1812 Adds export of point and polygon transparency and stroke transparency.
  v3/src/components/graph/v2-graph-importer.ts
  v3/src/components/map/v2-map-exporter.ts
  v3/src/components/map/v2-map-importer.test.ts
  v3/src/components/map/v2-map-importer.ts
  v3/src/test/v2/roller-coasters-map-layer-formats.codap
  v3/src/test/v2/roller-coasters-map-measures.codap
  v3/src/test/v2/roller-coasters-map.codap
Labels: v3, run regression

#1820 Plot "0" in dot charts
  v3/src/components/data-display/models/data-configuration-model.ts
Labels: v3, run regression

#1821 staging build 3.0.0-pre.2183
  v3/CHANGELOG.md
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1822 Fix bar chart (line chart) rendering on restore
  v3/src/components/data-display/pixi/pixi-points.ts
Labels: v3

#1823 Fix date-to-categorical axis bug
  v3/src/components/axis/helper-models/date-axis-helper.ts
  v3/src/components/axis/hooks/use-sub-axis.ts
Labels: v3

#1824 Fix to categorical axis update bug
  v3/src/components/axis/hooks/use-sub-axis.ts
Labels: v3

#1817 fix: first() and last() functions
  v3/src/models/formula/functions/aggregate-functions.ts
  v3/src/models/formula/functions/local-lookup-functions.test.ts
  v3/src/models/formula/functions/local-lookup-functions.ts
  v3/src/models/formula/functions/math.ts
Labels: v3, run regression

#1797 add option to use quantized choropleth legend
  v3/cypress/e2e/graph-legend.spec.ts
  v3/cypress/e2e/graph.spec.ts
  v3/src/components/data-display/components/legend/choropleth-legend/choropleth-legend.ts
  v3/src/components/data-display/components/legend/numeric-legend.tsx
  v3/src/components/data-display/inspector/display-item-format-control.tsx
  v3/src/components/data-display/models/data-configuration-model.ts
  v3/src/components/graph/hooks/use-plot.ts
  v3/src/components/map/components/map-point-layer.tsx
  v3/src/models/codap/create-codap-document.test.ts
  v3/src/models/data/category-set.ts
  v3/src/models/shared/shared-case-metadata.ts
  v3/src/utilities/color-utils.ts
  v3/src/utilities/math-utils.ts
  v3/src/utilities/translation/lang/en-US.json5
Labels: v3, run regression

#1819 Matches table collection colors to case card collection colors
  v3/src/components/case-card/case-card-header.tsx
  v3/src/components/case-card/case-card.scss
  v3/src/components/case-card/case-view.scss
  v3/src/components/case-card/case-view.tsx
  v3/src/components/case-table/case-table.scss
  v3/src/components/case-table/case-table.tsx
  v3/src/components/case-table/collection-table.tsx
  v3/src/components/case-tile-common/case-tile-utils.ts
  v3/src/components/case-tile-common/case-tile-vars.scss
  v3/src/components/case-tile-common/collection-title.tsx
Labels: v3, run regression

#1827 feat: `levelColors` url parameter changes order of collection color assignments
  v3/src/components/case-card/case-view.tsx
  v3/src/components/case-tile-common/case-tile-utils.ts
  v3/src/components/case-tile-common/collection-title.tsx
  v3/src/utilities/url-params.ts
Labels: v3, run regression

#1831 staging build 3.0.0-pre.2190
  v3/CHANGELOG.md
  v3/cypress/e2e/slider.spec.ts
  v3/package-lock.json
  v3/package.json
  v3/versions.md
Labels: v3, run regression

#1830 fix: restore of graph adornments
  v3/src/components/axis/models/multi-scale.ts
  v3/src/components/graph/adornments/univariate-measures/univariate-measure-adornment-helper.ts
Labels: v3, run regression
